"use client";

import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, FilePlus2, RefreshCw, Send, UploadCloud } from "lucide-react";
import type { AdminKnowledgeContent, AdminKnowledgeList } from "@ninibu/types";
import { clientApi } from "@/lib/client-api";
import { Button } from "@/components/ui/button";
import { Field } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { AdminCard, AdminEmpty, AdminError, AdminModal, AdminPageHeader, AdminStatus, formatAdminDate } from "@/components/admin/common";

type ContentForm = { content_type: string; slug: string; title: string; summary: string; body: string; medical_review_required: boolean; source_title: string; source_publisher: string; source_url: string; source_type: string };
const blank: ContentForm = { content_type: "guide", slug: "", title: "", summary: "", body: "", medical_review_required: false, source_title: "", source_publisher: "", source_url: "", source_type: "guideline" };

export function AdminContentPanel() {
  const qc = useQueryClient();
  const [search, setSearch] = useState("");
  const [type, setType] = useState("");
  const [createOpen, setCreateOpen] = useState(false);
  const [form, setForm] = useState<ContentForm>(blank);
  const [revisionFor, setRevisionFor] = useState<AdminKnowledgeContent>();
  const [revision, setRevision] = useState({ title: "", summary: "", body: "", change_note: "", source_title: "", source_publisher: "", source_url: "", source_type: "guideline" });
  const qs = useMemo(() => new URLSearchParams({ limit: "100", ...(search ? { search } : {}), ...(type ? { content_type: type } : {}) }).toString(), [search, type]);
  const query = useQuery({ queryKey: ["admin", "content", qs], queryFn: () => clientApi<AdminKnowledgeList>(`/api/ninibu/admin/content?${qs}`) });
  const invalidate = () => qc.invalidateQueries({ queryKey: ["admin", "content"] });
  const action = useMutation({ mutationFn: ({ id, action }: { id: number; action: "submit-review" | "publish" | "archive" }) => clientApi(`/api/ninibu/admin/content/${id}/${action}`, { method: "POST", body: "{}" }), onSuccess: invalidate });
  const create = useMutation({ mutationFn: () => clientApi("/api/ninibu/admin/content", { method: "POST", body: JSON.stringify({ content_type: form.content_type, slug: form.slug.trim(), title: form.title.trim(), summary: form.summary.trim(), body: form.body, language: "fa", medical_review_required: form.medical_review_required, category_ids: [], tag_ids: [], disclaimer_codes: [], audience: null, sources: sourcePayload(form), faqs: [] }) }), onSuccess: () => { setCreateOpen(false); setForm(blank); void invalidate(); } });
  const revise = useMutation({ mutationFn: () => clientApi(`/api/ninibu/admin/content/${revisionFor!.id}/revisions`, { method: "POST", body: JSON.stringify({ title: revision.title, summary: revision.summary, body: revision.body, change_note: revision.change_note, sources: sourcePayload(revision), faqs: [] }) }), onSuccess: () => { setRevisionFor(undefined); void invalidate(); } });
  const mutationError = (create.error || revise.error || action.error) as Error | null;

  function openRevision(item: AdminKnowledgeContent) { setRevisionFor(item); setRevision({ title: item.title, summary: item.summary ?? "", body: "", change_note: "", source_title: "", source_publisher: "", source_url: "", source_type: "guideline" }); }
  return <div className="admin-page">
    <AdminPageHeader eyebrow="Knowledge Operations" title="مدیریت محتوا" description="تولید، نسخه‌بندی، بازبینی و انتشار محتوای عمومی. محتوای پزشکی بدون تأیید متخصص و منبع قابل انتشار نیست." actions={<Button onClick={() => setCreateOpen(true)}><FilePlus2 size={18}/> محتوای جدید</Button>} />
    <AdminCard className="admin-toolbar"><Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="جست‌وجوی عنوان یا خلاصه…"/><Select value={type} onChange={(e) => setType(e.target.value)}><option value="">همه نوع‌ها</option><option value="article">مقاله</option><option value="guide">راهنما</option><option value="faq">پرسش متداول</option><option value="educational">آموزشی</option><option value="checklist">چک‌لیست</option><option value="announcement">اعلان</option></Select><Button variant="outline" onClick={() => query.refetch()}><RefreshCw size={17}/> بروزرسانی</Button></AdminCard>
    {query.isError ? <AdminError message="فهرست محتوا دریافت نشد."/> : null}{mutationError ? <AdminError message={mutationError.message}/> : null}
    <AdminCard className="admin-table-card"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>محتوا</th><th>نوع</th><th>وضعیت</th><th>بازبینی پزشکی</th><th>آخرین تغییر</th><th>عملیات</th></tr></thead><tbody>{query.data?.items.map((item) => <tr key={item.id}><td><strong>{item.title}</strong><small>{item.slug}</small></td><td>{contentTypeLabel(item.content_type)}</td><td><AdminStatus value={item.status}/></td><td>{item.medical_review_required ? <span className="admin-chip medical">الزامی</span> : <span className="admin-chip">عادی</span>}</td><td>{formatAdminDate(item.updated_at)}</td><td><div className="admin-row-actions"><Button variant="ghost" onClick={() => openRevision(item)}>نسخه جدید</Button>{item.status !== "archived" ? <><Button variant="outline" onClick={() => action.mutate({ id: item.id, action: "submit-review" })}><Send size={15}/> بررسی</Button><Button onClick={() => action.mutate({ id: item.id, action: "publish" })}><UploadCloud size={15}/> انتشار</Button><Button variant="ghost" onClick={() => action.mutate({ id: item.id, action: "archive" })}><Archive size={15}/></Button></> : null}</div></td></tr>)}</tbody></table></div>{!query.isLoading && !query.data?.items.length ? <AdminEmpty title="محتوایی پیدا نشد" description="فیلتر را تغییر دهید یا محتوای جدید بسازید."/> : null}</AdminCard>
    {createOpen ? <AdminModal title="محتوای جدید" description="نسخه اول به صورت پیش‌نویس ذخیره می‌شود." onClose={() => setCreateOpen(false)} footer={<><Button variant="outline" onClick={() => setCreateOpen(false)}>انصراف</Button><Button disabled={create.isPending || !form.slug.trim() || !form.title.trim() || !form.body.trim()} onClick={() => create.mutate()}>ذخیره پیش‌نویس</Button></>}><ContentFields value={form} onChange={setForm}/></AdminModal> : null}
    {revisionFor ? <AdminModal title={`نسخه جدید: ${revisionFor.title}`} description="نسخه منتشرشده فعلی تا انتشار نسخه جدید دست‌نخورده می‌ماند." onClose={() => setRevisionFor(undefined)} footer={<><Button variant="outline" onClick={() => setRevisionFor(undefined)}>انصراف</Button><Button disabled={revise.isPending || !revision.title.trim() || !revision.body.trim()} onClick={() => revise.mutate()}>ساخت نسخه</Button></>}><div className="admin-form-grid"><Field label="عنوان"><Input value={revision.title} onChange={(e) => setRevision({ ...revision, title: e.target.value })}/></Field><Field label="یادداشت تغییر"><Input value={revision.change_note} onChange={(e) => setRevision({ ...revision, change_note: e.target.value })}/></Field><Field label="خلاصه"><Textarea value={revision.summary} onChange={(e) => setRevision({ ...revision, summary: e.target.value })}/></Field><Field label="متن کامل"><Textarea className="admin-long-textarea" value={revision.body} onChange={(e) => setRevision({ ...revision, body: e.target.value })}/></Field><SourceFields value={revision} onChange={setRevision}/></div></AdminModal> : null}
  </div>;
}

function ContentFields({ value, onChange }: { value: ContentForm; onChange: (x: ContentForm) => void }) { return <div className="admin-form-grid"><Field label="نوع محتوا"><Select value={value.content_type} onChange={(e) => onChange({ ...value, content_type: e.target.value })}><option value="guide">راهنما</option><option value="article">مقاله</option><option value="educational">آموزشی</option><option value="faq">FAQ</option><option value="checklist">چک‌لیست</option><option value="reference">مرجع</option><option value="announcement">اعلان</option></Select></Field><Field label="Slug"><Input dir="ltr" value={value.slug} onChange={(e) => onChange({ ...value, slug: e.target.value })} placeholder="breastfeeding-basics"/></Field><Field label="عنوان"><Input value={value.title} onChange={(e) => onChange({ ...value, title: e.target.value })}/></Field><label className="admin-check"><input type="checkbox" checked={value.medical_review_required} onChange={(e) => onChange({ ...value, medical_review_required: e.target.checked })}/><span><strong>نیازمند بازبینی پزشکی</strong><small>انتشار فقط پس از تأیید متخصص و وجود منبع</small></span></label><Field label="خلاصه"><Textarea value={value.summary} onChange={(e) => onChange({ ...value, summary: e.target.value })}/></Field><Field label="متن کامل"><Textarea className="admin-long-textarea" value={value.body} onChange={(e) => onChange({ ...value, body: e.target.value })}/></Field><SourceFields value={value} onChange={onChange}/></div>; }
function SourceFields<T extends { source_title: string; source_publisher: string; source_url: string; source_type: string }>({ value, onChange }: { value: T; onChange: (x: T) => void }) { return <fieldset className="admin-fieldset"><legend>منبع علمی (برای محتوای پزشکی لازم است)</legend><Field label="عنوان منبع"><Input value={value.source_title} onChange={(e) => onChange({ ...value, source_title: e.target.value })}/></Field><Field label="ناشر"><Input value={value.source_publisher} onChange={(e) => onChange({ ...value, source_publisher: e.target.value })}/></Field><Field label="URL"><Input dir="ltr" value={value.source_url} onChange={(e) => onChange({ ...value, source_url: e.target.value })}/></Field><Field label="نوع"><Select value={value.source_type} onChange={(e) => onChange({ ...value, source_type: e.target.value })}><option value="guideline">Guideline</option><option value="journal">Journal</option><option value="official">Official</option><option value="book">Book</option></Select></Field></fieldset>; }
function sourcePayload(value: { source_title: string; source_publisher: string; source_url: string; source_type: string }) { return value.source_title.trim() ? [{ title: value.source_title.trim(), publisher: value.source_publisher.trim(), url: value.source_url.trim(), source_type: value.source_type, publication_date: null, accessed_at: new Date().toISOString() }] : []; }
function contentTypeLabel(v: string) { return ({ guide: "راهنما", article: "مقاله", educational: "آموزشی", faq: "FAQ", checklist: "چک‌لیست", reference: "مرجع", announcement: "اعلان" } as Record<string,string>)[v] ?? v; }
