"use client";

import { useMemo, useRef, useState, type RefObject } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, FilePlus2, FolderTree, Pencil, Plus, RefreshCw, Send, Tags, Trash2, UploadCloud } from "lucide-react";
import type { AdminKnowledgeCategory, AdminKnowledgeContent, AdminKnowledgeList, AdminKnowledgeTag, AdminMediaList, KnowledgeDetail } from "@ninibu/types";
import { clientApi } from "@/lib/client-api";
import { Button } from "@/components/ui/button";
import { Field } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { AdminCard, AdminEmpty, AdminError, AdminModal, AdminPageHeader, AdminStatus, formatAdminDate } from "@/components/admin/common";
import { RichTextEditor, type RichTextEditorHandle } from "@/components/admin/rich-text-editor";

type Tab="contents"|"categories"|"tags";
type ContentForm={content_type:string;slug:string;title:string;summary:string;body:string;medical_review_required:boolean;category_ids:number[];tag_ids:number[];min_age_days:string;max_age_days:string;source_title:string;source_publisher:string;source_url:string;source_type:string};
const blank:ContentForm={content_type:"guide",slug:"",title:"",summary:"",body:"",medical_review_required:false,category_ids:[],tag_ids:[],min_age_days:"",max_age_days:"",source_title:"",source_publisher:"",source_url:"",source_type:"guideline"};
type RevisionForm={title:string;summary:string;body:string;change_note:string;source_title:string;source_publisher:string;source_url:string;source_type:string};
type MetadataForm={content_type:string;slug:string;language:string;medical_review_required:boolean;category_ids:number[];tag_ids:number[];min_age_days:string;max_age_days:string};

export function AdminContentPanel(){
  const qc=useQueryClient(); const editorRef=useRef<RichTextEditorHandle>(null); const revisionEditorRef=useRef<RichTextEditorHandle>(null);
  const [tab,setTab]=useState<Tab>("contents"); const [search,setSearch]=useState(""); const [type,setType]=useState(""); const [createOpen,setCreateOpen]=useState(false); const [form,setForm]=useState<ContentForm>(blank); const [revisionFor,setRevisionFor]=useState<AdminKnowledgeContent>(); const [revision,setRevision]=useState<RevisionForm>({title:"",summary:"",body:"",change_note:"",source_title:"",source_publisher:"",source_url:"",source_type:"guideline"}); const [metadataFor,setMetadataFor]=useState<AdminKnowledgeContent>(); const [metadata,setMetadata]=useState<MetadataForm>({content_type:"guide",slug:"",language:"fa",medical_review_required:false,category_ids:[],tag_ids:[],min_age_days:"",max_age_days:""}); const [loadingDetail,setLoadingDetail]=useState(false); const [mediaId,setMediaId]=useState("");
  const [categoryEdit,setCategoryEdit]=useState<AdminKnowledgeCategory|"new">(); const [categoryForm,setCategoryForm]=useState({parent_id:"",code:"",slug:"",name:"",description:"",sort_order:"0",is_active:true}); const [tagEdit,setTagEdit]=useState<AdminKnowledgeTag|"new">(); const [tagForm,setTagForm]=useState({code:"",slug:"",name:"",is_active:true});
  const qs=useMemo(()=>new URLSearchParams({limit:"100",...(search?{search}:{}),...(type?{content_type:type}:{})}).toString(),[search,type]);
  const query=useQuery({queryKey:["admin","content",qs],queryFn:()=>clientApi<AdminKnowledgeList>(`/api/ninibu/admin/content?${qs}`)});
  const categories=useQuery({queryKey:["admin","content-categories"],queryFn:()=>clientApi<AdminKnowledgeCategory[]>("/api/ninibu/admin/content-categories")});
  const tags=useQuery({queryKey:["admin","content-tags"],queryFn:()=>clientApi<AdminKnowledgeTag[]>("/api/ninibu/admin/content-tags")});
  const media=useQuery({queryKey:["admin","media","editor"],queryFn:()=>clientApi<AdminMediaList>("/api/ninibu/admin/media?media_type=image&review_status=approved&limit=100")});
  const invalidate=()=>qc.invalidateQueries({queryKey:["admin","content"]}); const invalidateTax=()=>{void qc.invalidateQueries({queryKey:["admin","content-categories"]});void qc.invalidateQueries({queryKey:["admin","content-tags"]});};
  const action=useMutation({mutationFn:({id,action}:{id:number;action:"submit-review"|"publish"|"archive"})=>clientApi(`/api/ninibu/admin/content/${id}/${action}`,{method:"POST",body:"{}"}),onSuccess:invalidate});
  const create=useMutation({mutationFn:()=>clientApi("/api/ninibu/admin/content",{method:"POST",body:JSON.stringify({content_type:form.content_type,slug:form.slug.trim(),title:form.title.trim(),summary:form.summary.trim(),body:form.body,language:"fa",medical_review_required:form.medical_review_required,category_ids:form.category_ids,tag_ids:form.tag_ids,disclaimer_codes:[],audience:audiencePayload(form.min_age_days,form.max_age_days),sources:sourcePayload(form),faqs:[]})}),onSuccess:()=>{setCreateOpen(false);setForm(blank);void invalidate();}});
  const revise=useMutation({mutationFn:()=>clientApi(`/api/ninibu/admin/content/${revisionFor!.id}/revisions`,{method:"POST",body:JSON.stringify({title:revision.title,summary:revision.summary,body:revision.body,change_note:revision.change_note,sources:sourcePayload(revision),faqs:[]})}),onSuccess:()=>{setRevisionFor(undefined);void invalidate();}});
  const updateMeta=useMutation({mutationFn:()=>clientApi(`/api/ninibu/admin/content/${metadataFor!.id}`,{method:"PATCH",body:JSON.stringify({content_type:metadata.content_type,slug:metadata.slug.trim(),language:metadata.language,medical_review_required:metadata.medical_review_required,category_ids:metadata.category_ids,tag_ids:metadata.tag_ids,disclaimer_codes:[],audience:audiencePayload(metadata.min_age_days,metadata.max_age_days)})}),onSuccess:()=>{setMetadataFor(undefined);void invalidate();}});
  const remove=useMutation({mutationFn:(id:number)=>clientApi(`/api/ninibu/admin/content/${id}`,{method:"DELETE"}),onSuccess:invalidate});
  const saveCategory=useMutation({mutationFn:()=>clientApi(categoryEdit==="new"?"/api/ninibu/admin/content-categories":`/api/ninibu/admin/content-categories/${categoryEdit!.id}`,{method:categoryEdit==="new"?"POST":"PATCH",body:JSON.stringify({parent_id:categoryForm.parent_id?Number(categoryForm.parent_id):null,code:categoryForm.code.trim(),slug:categoryForm.slug.trim(),name:categoryForm.name.trim(),description:categoryForm.description.trim(),sort_order:Number(categoryForm.sort_order)||0,is_active:categoryForm.is_active})}),onSuccess:()=>{setCategoryEdit(undefined);invalidateTax();}});
  const deleteCategory=useMutation({mutationFn:(id:number)=>clientApi(`/api/ninibu/admin/content-categories/${id}`,{method:"DELETE"}),onSuccess:invalidateTax});
  const saveTag=useMutation({mutationFn:()=>clientApi(tagEdit==="new"?"/api/ninibu/admin/content-tags":`/api/ninibu/admin/content-tags/${tagEdit!.id}`,{method:tagEdit==="new"?"POST":"PATCH",body:JSON.stringify({...tagForm,code:tagForm.code.trim(),slug:tagForm.slug.trim(),name:tagForm.name.trim()})}),onSuccess:()=>{setTagEdit(undefined);invalidateTax();}});
  const deleteTag=useMutation({mutationFn:(id:number)=>clientApi(`/api/ninibu/admin/content-tags/${id}`,{method:"DELETE"}),onSuccess:invalidateTax});
  const mutationError=(create.error||revise.error||action.error||updateMeta.error||remove.error||saveCategory.error||deleteCategory.error||saveTag.error||deleteTag.error) as Error|null;

  async function openRevision(item:AdminKnowledgeContent){setLoadingDetail(true);try{const d=await clientApi<KnowledgeDetail>(`/api/ninibu/admin/content/${item.id}`);setRevisionFor(item);setRevision({title:d.revision.title,summary:d.revision.summary||"",body:d.revision.body,change_note:"",source_title:d.sources[0]?.title||"",source_publisher:d.sources[0]?.publisher||"",source_url:d.sources[0]?.url||"",source_type:d.sources[0]?.source_type||"guideline"});setMediaId("");}finally{setLoadingDetail(false)}}
  async function openMetadata(item:AdminKnowledgeContent){setLoadingDetail(true);try{const d=await clientApi<KnowledgeDetail>(`/api/ninibu/admin/content/${item.id}`);setMetadataFor(item);setMetadata({content_type:item.content_type,slug:item.slug,language:item.language||"fa",medical_review_required:item.medical_review_required,category_ids:d.categories.map(x=>x.id),tag_ids:d.tags.map(x=>x.id),min_age_days:d.audience?.min_child_age_days!=null?String(d.audience.min_child_age_days):"",max_age_days:d.audience?.max_child_age_days!=null?String(d.audience.max_child_age_days):""});}finally{setLoadingDetail(false)}}
  function insertSelected(editor:RichTextEditorHandle|null){const item=media.data?.items.find(x=>String(x.id)===mediaId);if(item)editor?.insertMedia(item)}
  function openCategory(item?:AdminKnowledgeCategory){if(!item){setCategoryEdit("new");setCategoryForm({parent_id:"",code:"",slug:"",name:"",description:"",sort_order:"0",is_active:true})}else{setCategoryEdit(item);setCategoryForm({parent_id:item.parent_id?String(item.parent_id):"",code:item.code,slug:item.slug,name:item.name,description:item.description||"",sort_order:String(item.sort_order||0),is_active:item.is_active})}}
  function openTag(item?:AdminKnowledgeTag){if(!item){setTagEdit("new");setTagForm({code:"",slug:"",name:"",is_active:true})}else{setTagEdit(item);setTagForm({code:item.code,slug:item.slug,name:item.name,is_active:item.is_active})}}

  return <div className="admin-page">
    <AdminPageHeader eyebrow="Knowledge Operations" title="مدیریت محتوا" description="CMS نینیبو برای تولید، طبقه‌بندی، نسخه‌بندی، بازبینی پزشکی و انتشار. متن غنی و رسانه‌ها از همین پنل مدیریت می‌شوند." actions={tab==="contents"?<Button onClick={()=>setCreateOpen(true)}><FilePlus2 size={18}/> محتوای جدید</Button>:tab==="categories"?<Button onClick={()=>openCategory()}><Plus size={18}/> دسته جدید</Button>:<Button onClick={()=>openTag()}><Plus size={18}/> برچسب جدید</Button>}/>
    <div className="admin-tabs"><button className={tab==="contents"?"active":""} onClick={()=>setTab("contents")}>مطالب</button><button className={tab==="categories"?"active":""} onClick={()=>setTab("categories")}><FolderTree size={14}/> دسته‌بندی‌ها</button><button className={tab==="tags"?"active":""} onClick={()=>setTab("tags")}><Tags size={14}/> برچسب‌ها</button></div>
    {mutationError?<AdminError message={mutationError.message}/>:null}
    {tab==="contents"?<><AdminCard className="admin-toolbar"><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="جست‌وجوی عنوان یا خلاصه…"/><Select value={type} onChange={e=>setType(e.target.value)}><option value="">همه نوع‌ها</option>{contentTypeOptions()}</Select><Button variant="outline" onClick={()=>query.refetch()}><RefreshCw size={17}/> بروزرسانی</Button></AdminCard>{query.isError?<AdminError message="فهرست محتوا دریافت نشد."/>:null}<AdminCard className="admin-table-card"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>محتوا</th><th>نوع</th><th>وضعیت</th><th>بازبینی پزشکی</th><th>آخرین تغییر</th><th>عملیات</th></tr></thead><tbody>{query.data?.items.map(item=><tr key={item.id}><td><strong>{item.title}</strong><small>{item.slug}</small></td><td>{contentTypeLabel(item.content_type)}</td><td><AdminStatus value={item.status}/></td><td>{item.medical_review_required?<span className="admin-chip medical">الزامی</span>:<span className="admin-chip">عادی</span>}</td><td>{formatAdminDate(item.updated_at)}</td><td><div className="admin-row-actions"><Button variant="ghost" disabled={loadingDetail} onClick={()=>void openRevision(item)}>ویرایش متن</Button><Button variant="ghost" disabled={loadingDetail} onClick={()=>void openMetadata(item)}><Pencil size={14}/> مشخصات</Button>{item.status!=="archived"?<><Button variant="outline" onClick={()=>action.mutate({id:item.id,action:"submit-review"})}><Send size={15}/> بررسی</Button><Button onClick={()=>action.mutate({id:item.id,action:"publish"})}><UploadCloud size={15}/> انتشار</Button><Button variant="ghost" onClick={()=>action.mutate({id:item.id,action:"archive"})}><Archive size={15}/></Button>{item.status!=="published"?<Button variant="ghost" onClick={()=>{if(window.confirm("این مطلب حذف شود؟"))remove.mutate(item.id)}}><Trash2 size={15}/></Button>:null}</>:<Button variant="ghost" onClick={()=>{if(window.confirm("این مطلب آرشیوشده برای همیشه از فهرست مدیریت حذف شود؟"))remove.mutate(item.id)}}><Trash2 size={15}/> حذف</Button>}</div></td></tr>)}</tbody></table></div>{!query.isLoading&&!query.data?.items.length?<AdminEmpty title="محتوایی پیدا نشد" description="فیلتر را تغییر دهید یا محتوای جدید بسازید."/>:null}</AdminCard></>:null}
    {tab==="categories"?<TaxonomyTable kind="category" items={categories.data||[]} loading={categories.isLoading} onEdit={x=>openCategory(x as AdminKnowledgeCategory)} onDelete={id=>{if(window.confirm("این دسته حذف شود؟"))deleteCategory.mutate(id)}}/>:null}
    {tab==="tags"?<TaxonomyTable kind="tag" items={tags.data||[]} loading={tags.isLoading} onEdit={x=>openTag(x as AdminKnowledgeTag)} onDelete={id=>{if(window.confirm("این برچسب حذف شود؟"))deleteTag.mutate(id)}}/>:null}

    {createOpen?<AdminModal title="محتوای جدید" description="نسخه اول به صورت پیش‌نویس ذخیره می‌شود." onClose={()=>setCreateOpen(false)} footer={<><Button variant="outline" onClick={()=>setCreateOpen(false)}>انصراف</Button><Button disabled={create.isPending||!form.slug.trim()||!form.title.trim()||!textHasContent(form.body)} onClick={()=>create.mutate()}>ذخیره پیش‌نویس</Button></>}><ContentFields value={form} onChange={setForm} categories={categories.data||[]} tags={tags.data||[]} editorRef={editorRef} mediaId={mediaId} setMediaId={setMediaId} media={media.data?.items||[]} onInsert={()=>insertSelected(editorRef.current)}/></AdminModal>:null}
    {revisionFor?<AdminModal title={`ویرایش متن: ${revisionFor.title}`} description="این ویرایش یک Revision جدید می‌سازد؛ نسخه منتشرشده تا انتشار Revision جدید دست‌نخورده می‌ماند." onClose={()=>setRevisionFor(undefined)} footer={<><Button variant="outline" onClick={()=>setRevisionFor(undefined)}>انصراف</Button><Button disabled={revise.isPending||!revision.title.trim()||!textHasContent(revision.body)} onClick={()=>revise.mutate()}>ساخت Revision</Button></>}><div className="admin-form-grid"><Field label="عنوان"><Input value={revision.title} onChange={e=>setRevision({...revision,title:e.target.value})}/></Field><Field label="یادداشت تغییر"><Input value={revision.change_note} onChange={e=>setRevision({...revision,change_note:e.target.value})}/></Field><Field label="خلاصه"><Textarea value={revision.summary} onChange={e=>setRevision({...revision,summary:e.target.value})}/></Field><div className="admin-span-2"><RichTextEditor ref={revisionEditorRef} value={revision.body} onChange={body=>setRevision({...revision,body})}/><MediaInsertBar media={media.data?.items||[]} value={mediaId} onChange={setMediaId} onInsert={()=>insertSelected(revisionEditorRef.current)}/></div><SourceFields value={revision} onChange={setRevision}/></div></AdminModal>:null}
    {metadataFor?<AdminModal title={`مشخصات: ${metadataFor.title}`} description="این فرم ساختار و هدف‌گیری مطلب را تغییر می‌دهد و متن Revision را دست نمی‌زند." onClose={()=>setMetadataFor(undefined)} footer={<><Button variant="outline" onClick={()=>setMetadataFor(undefined)}>انصراف</Button><Button disabled={updateMeta.isPending||!metadata.slug.trim()} onClick={()=>updateMeta.mutate()}>ذخیره مشخصات</Button></>}><MetadataFields value={metadata} onChange={setMetadata} categories={categories.data||[]} tags={tags.data||[]}/></AdminModal>:null}
    {categoryEdit?<AdminModal title={categoryEdit==="new"?"دسته جدید":"ویرایش دسته"} onClose={()=>setCategoryEdit(undefined)} footer={<><Button variant="outline" onClick={()=>setCategoryEdit(undefined)}>انصراف</Button><Button disabled={!categoryForm.code.trim()||!categoryForm.slug.trim()||!categoryForm.name.trim()||saveCategory.isPending} onClick={()=>saveCategory.mutate()}>ذخیره</Button></>}><div className="admin-form-grid"><Field label="نام"><Input value={categoryForm.name} onChange={e=>setCategoryForm({...categoryForm,name:e.target.value})}/></Field><Field label="Code"><Input dir="ltr" value={categoryForm.code} onChange={e=>setCategoryForm({...categoryForm,code:e.target.value})}/></Field><Field label="Slug"><Input dir="ltr" value={categoryForm.slug} onChange={e=>setCategoryForm({...categoryForm,slug:e.target.value})}/></Field><Field label="Parent ID"><Input inputMode="numeric" value={categoryForm.parent_id} onChange={e=>setCategoryForm({...categoryForm,parent_id:e.target.value})}/></Field><Field label="ترتیب"><Input inputMode="numeric" value={categoryForm.sort_order} onChange={e=>setCategoryForm({...categoryForm,sort_order:e.target.value})}/></Field><Field label="توضیح"><Textarea value={categoryForm.description} onChange={e=>setCategoryForm({...categoryForm,description:e.target.value})}/></Field><label className="admin-check"><input type="checkbox" checked={categoryForm.is_active} onChange={e=>setCategoryForm({...categoryForm,is_active:e.target.checked})}/><span><strong>فعال</strong><small>در انتخاب‌های عمومی نمایش داده شود.</small></span></label></div></AdminModal>:null}
    {tagEdit?<AdminModal title={tagEdit==="new"?"برچسب جدید":"ویرایش برچسب"} onClose={()=>setTagEdit(undefined)} footer={<><Button variant="outline" onClick={()=>setTagEdit(undefined)}>انصراف</Button><Button disabled={!tagForm.code.trim()||!tagForm.slug.trim()||!tagForm.name.trim()||saveTag.isPending} onClick={()=>saveTag.mutate()}>ذخیره</Button></>}><div className="admin-form-grid"><Field label="نام"><Input value={tagForm.name} onChange={e=>setTagForm({...tagForm,name:e.target.value})}/></Field><Field label="Code"><Input dir="ltr" value={tagForm.code} onChange={e=>setTagForm({...tagForm,code:e.target.value})}/></Field><Field label="Slug"><Input dir="ltr" value={tagForm.slug} onChange={e=>setTagForm({...tagForm,slug:e.target.value})}/></Field><label className="admin-check"><input type="checkbox" checked={tagForm.is_active} onChange={e=>setTagForm({...tagForm,is_active:e.target.checked})}/><span><strong>فعال</strong><small>در فیلترها و جست‌وجو قابل استفاده باشد.</small></span></label></div></AdminModal>:null}
  </div>
}

function ContentFields({value,onChange,categories,tags,editorRef,mediaId,setMediaId,media,onInsert}:{value:ContentForm;onChange:(v:ContentForm)=>void;categories:AdminKnowledgeCategory[];tags:AdminKnowledgeTag[];editorRef:RefObject<RichTextEditorHandle|null>;mediaId:string;setMediaId:(v:string)=>void;media:AdminMediaList["items"];onInsert:()=>void}){return <div className="admin-form-grid"><Field label="نوع محتوا"><Select value={value.content_type} onChange={e=>onChange({...value,content_type:e.target.value})}>{contentTypeOptions()}</Select></Field><Field label="Slug"><Input dir="ltr" value={value.slug} onChange={e=>onChange({...value,slug:e.target.value})} placeholder="newborn-safe-sleep"/></Field><Field label="عنوان"><Input value={value.title} onChange={e=>onChange({...value,title:e.target.value})}/></Field><Field label="خلاصه"><Textarea value={value.summary} onChange={e=>onChange({...value,summary:e.target.value})}/></Field><TaxonomyPicker title="دسته‌بندی‌ها" items={categories} selected={value.category_ids} onChange={ids=>onChange({...value,category_ids:ids})}/><TaxonomyPicker title="برچسب‌ها" items={tags} selected={value.tag_ids} onChange={ids=>onChange({...value,tag_ids:ids})}/><fieldset className="admin-fieldset"><legend>مخاطب سنی</legend><Field label="حداقل سن کودک (روز)"><Input inputMode="numeric" value={value.min_age_days} onChange={e=>onChange({...value,min_age_days:e.target.value})}/></Field><Field label="حداکثر سن کودک (روز)"><Input inputMode="numeric" value={value.max_age_days} onChange={e=>onChange({...value,max_age_days:e.target.value})}/></Field></fieldset><label className="admin-check"><input type="checkbox" checked={value.medical_review_required} onChange={e=>onChange({...value,medical_review_required:e.target.checked})}/><span><strong>بازبینی پزشکی الزامی</strong><small>انتشار تا تأیید متخصص ممکن نیست.</small></span></label><div className="admin-span-2"><RichTextEditor ref={editorRef} value={value.body} onChange={body=>onChange({...value,body})}/><MediaInsertBar media={media} value={mediaId} onChange={setMediaId} onInsert={onInsert}/></div><SourceFields value={value} onChange={onChange}/></div>}
function MetadataFields({value,onChange,categories,tags}:{value:MetadataForm;onChange:(v:MetadataForm)=>void;categories:AdminKnowledgeCategory[];tags:AdminKnowledgeTag[]}){return <div className="admin-form-grid"><Field label="نوع محتوا"><Select value={value.content_type} onChange={e=>onChange({...value,content_type:e.target.value})}>{contentTypeOptions()}</Select></Field><Field label="Slug"><Input dir="ltr" value={value.slug} onChange={e=>onChange({...value,slug:e.target.value})}/></Field><Field label="زبان"><Select value={value.language} onChange={e=>onChange({...value,language:e.target.value})}><option value="fa">فارسی</option><option value="en">English</option></Select></Field><label className="admin-check"><input type="checkbox" checked={value.medical_review_required} onChange={e=>onChange({...value,medical_review_required:e.target.checked})}/><span><strong>بازبینی پزشکی الزامی</strong><small>Workflow انتشار مطابق محتوای پزشکی اعمال شود.</small></span></label><TaxonomyPicker title="دسته‌بندی‌ها" items={categories} selected={value.category_ids} onChange={ids=>onChange({...value,category_ids:ids})}/><TaxonomyPicker title="برچسب‌ها" items={tags} selected={value.tag_ids} onChange={ids=>onChange({...value,tag_ids:ids})}/><fieldset className="admin-fieldset"><legend>مخاطب سنی</legend><Field label="حداقل سن کودک (روز)"><Input inputMode="numeric" value={value.min_age_days} onChange={e=>onChange({...value,min_age_days:e.target.value})}/></Field><Field label="حداکثر سن کودک (روز)"><Input inputMode="numeric" value={value.max_age_days} onChange={e=>onChange({...value,max_age_days:e.target.value})}/></Field></fieldset></div>}
function SourceFields<T extends {source_title:string;source_publisher:string;source_url:string;source_type:string}>({value,onChange}:{value:T;onChange:(v:T)=>void}){return <fieldset className="admin-fieldset"><legend>منبع اصلی</legend><Field label="عنوان منبع"><Input value={value.source_title} onChange={e=>onChange({...value,source_title:e.target.value})}/></Field><Field label="ناشر"><Input value={value.source_publisher} onChange={e=>onChange({...value,source_publisher:e.target.value})}/></Field><Field label="URL"><Input dir="ltr" value={value.source_url} onChange={e=>onChange({...value,source_url:e.target.value})}/></Field><Field label="نوع"><Select value={value.source_type} onChange={e=>onChange({...value,source_type:e.target.value})}><option value="guideline">Guideline</option><option value="journal">Journal</option><option value="official">Official</option><option value="book">Book</option></Select></Field></fieldset>}
function TaxonomyPicker({title,items,selected,onChange}:{title:string;items:Array<{id:number;name:string;is_active:boolean}>;selected:number[];onChange:(v:number[])=>void}){return <fieldset className="admin-fieldset admin-taxonomy-picker"><legend>{title}</legend><div>{items.filter(x=>x.is_active).map(item=><label key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={e=>onChange(e.target.checked?[...selected,item.id]:selected.filter(id=>id!==item.id))}/><span>{item.name}</span></label>)}</div></fieldset>}
function MediaInsertBar({media,value,onChange,onInsert}:{media:AdminMediaList["items"];value:string;onChange:(v:string)=>void;onInsert:()=>void}){return <div className="admin-media-insert"><Select value={value} onChange={e=>onChange(e.target.value)}><option value="">تصویر از Media Library…</option>{media.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</Select><Button variant="outline" disabled={!value} onClick={onInsert}>درج در متن</Button><small>فقط تصاویر تأییدشده نمایش داده می‌شوند.</small></div>}
function TaxonomyTable({kind,items,loading,onEdit,onDelete}:{kind:"category"|"tag";items:Array<AdminKnowledgeCategory|AdminKnowledgeTag>;loading:boolean;onEdit:(x:AdminKnowledgeCategory|AdminKnowledgeTag)=>void;onDelete:(id:number)=>void}){return <AdminCard className="admin-table-card"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>نام</th><th>Code</th><th>Slug</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><strong>{x.name}</strong>{kind==="category"&&"description" in x&&x.description?<small>{x.description}</small>:null}</td><td dir="ltr">{x.code}</td><td dir="ltr">{x.slug}</td><td><AdminStatus value={x.is_active}/></td><td><div className="admin-row-actions"><Button variant="outline" onClick={()=>onEdit(x)}><Pencil size={14}/> ویرایش</Button><Button variant="ghost" onClick={()=>onDelete(x.id)}><Trash2 size={14}/></Button></div></td></tr>)}</tbody></table></div>{!loading&&!items.length?<AdminEmpty title={kind==="category"?"دسته‌ای وجود ندارد":"برچسبی وجود ندارد"} description="از دکمه بالا اولین مورد را ایجاد کنید."/>:null}</AdminCard>}
function sourcePayload(v:{source_title:string;source_publisher:string;source_url:string;source_type:string}){return v.source_title.trim()?[{title:v.source_title.trim(),publisher:v.source_publisher.trim(),url:v.source_url.trim(),source_type:v.source_type,publication_date:null,accessed_at:new Date().toISOString()}]:[]}
function audiencePayload(min:string,max:string){const a=min.trim()?Number(min):undefined,b=max.trim()?Number(max):undefined;if(a===undefined&&b===undefined)return null;return {min_child_age_days:a!==undefined&&Number.isFinite(a)?a:null,max_child_age_days:b!==undefined&&Number.isFinite(b)?b:null,audience_type:"parent"}}
function contentTypeOptions(){return <><option value="article">مقاله</option><option value="guide">راهنما</option><option value="faq">پرسش متداول</option><option value="educational">آموزشی</option><option value="checklist">چک‌لیست</option><option value="reference">مرجع</option><option value="announcement">اعلان</option></>}
function contentTypeLabel(v:string){return ({guide:"راهنما",article:"مقاله",educational:"آموزشی",faq:"FAQ",checklist:"چک‌لیست",reference:"مرجع",announcement:"اعلان"} as Record<string,string>)[v]??v}
function textHasContent(html:string){return html.replace(/<[^>]+>/g,"").replaceAll("&nbsp;","").trim().length>0||/<img\b/i.test(html)}
