"use client";

import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { File, FileImage, Link2, Pencil, Plus, RefreshCw, Trash2, UploadCloud } from "lucide-react";
import type { AdminKnowledgeList, AdminMediaAsset, AdminMediaList } from "@ninibu/types";
import { clientApi } from "@/lib/client-api";
import { Button } from "@/components/ui/button";
import { Field } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { AdminCard, AdminEmpty, AdminError, AdminModal, AdminPageHeader, AdminStatus, formatAdminDate } from "@/components/admin/common";
import { resolveMediaUrl } from "@/components/admin/rich-text-editor";

const blankExternal = { content_id: "", media_type: "image", title: "", alt_text: "", asset_url: "", thumbnail_url: "", source_name: "", source_url: "", author: "", license_code: "", license_url: "", attribution_text: "", commercial_use_allowed: false, derivative_allowed: false, review_status: "source_review_required" };
type ExternalForm = typeof blankExternal;

export function AdminMediaPanel() {
  const qc = useQueryClient();
  const [search, setSearch] = useState(""); const [mediaType, setMediaType] = useState(""); const [status, setStatus] = useState("");
  const [uploadOpen, setUploadOpen] = useState(false); const [externalOpen, setExternalOpen] = useState(false); const [editing, setEditing] = useState<AdminMediaAsset>();
  const [file, setFile] = useState<File>(); const [uploadForm, setUploadForm] = useState({ content_id: "", title: "", alt_text: "", rights_confirmed: false });
  const [external, setExternal] = useState<ExternalForm>(blankExternal);
  const qs = useMemo(() => new URLSearchParams({ limit:"120", ...(search?{search}:{}), ...(mediaType?{media_type:mediaType}:{}), ...(status?{review_status:status}:{}) }).toString(), [search, mediaType, status]);
  const query = useQuery({ queryKey:["admin","media",qs], queryFn:()=>clientApi<AdminMediaList>(`/api/ninibu/admin/media?${qs}`) });
  const contents = useQuery({ queryKey:["admin","content","media-picker"], queryFn:()=>clientApi<AdminKnowledgeList>("/api/ninibu/admin/content?limit=200") });
  const invalidate=()=>qc.invalidateQueries({queryKey:["admin","media"]});

  const upload = useMutation({ mutationFn: async()=>{
    if(!file) throw new Error("فایل را انتخاب کنید.");
    const data=new FormData(); data.set("file",file); if(uploadForm.content_id)data.set("content_id",uploadForm.content_id); data.set("title",uploadForm.title); data.set("alt_text",uploadForm.alt_text); data.set("rights_confirmed",String(uploadForm.rights_confirmed));
    return clientApi<AdminMediaAsset>("/api/ninibu/admin/media/upload",{method:"POST",body:data});
  }, onSuccess:()=>{setUploadOpen(false);setFile(undefined);setUploadForm({content_id:"",title:"",alt_text:"",rights_confirmed:false});void invalidate();} });
  const create = useMutation({ mutationFn:()=>clientApi<AdminMediaAsset>("/api/ninibu/admin/media",{method:"POST",body:JSON.stringify(mediaPayload(external))}), onSuccess:()=>{setExternalOpen(false);setExternal(blankExternal);void invalidate();} });
  const update = useMutation({ mutationFn:()=>clientApi<AdminMediaAsset>(`/api/ninibu/admin/media/${editing!.id}`,{method:"PATCH",body:JSON.stringify(mediaPayload(external))}), onSuccess:()=>{setEditing(undefined);setExternal(blankExternal);void invalidate();} });
  const remove = useMutation({ mutationFn:(id:number)=>clientApi(`/api/ninibu/admin/media/${id}`,{method:"DELETE"}), onSuccess:invalidate });
  const error=(upload.error||create.error||update.error||remove.error) as Error|null;

  function openEdit(item:AdminMediaAsset){ setEditing(item); setExternal({ content_id:item.content_id?String(item.content_id):"", media_type:item.media_type,title:item.title,alt_text:item.alt_text||"",asset_url:item.asset_url||"",thumbnail_url:item.thumbnail_url||"",source_name:item.source_name||"",source_url:item.source_url||"",author:item.author||"",license_code:item.license_code||"",license_url:item.license_url||"",attribution_text:item.attribution_text||"",commercial_use_allowed:item.commercial_use_allowed,derivative_allowed:item.derivative_allowed,review_status:item.review_status }); }

  return <div className="admin-page">
    <AdminPageHeader eyebrow="Media Library" title="رسانه و فایل‌ها" description="کتابخانه مرکزی تصویر و فایل برای مطالب آموزشی. فایل داخلی فقط پس از تأیید حق انتشار آپلود می‌شود و برای رسانه خارجی، مجوز و منبع جداگانه ثبت می‌شود." actions={<><Button variant="outline" onClick={()=>setExternalOpen(true)}><Link2 size={17}/> رسانه با URL</Button><Button onClick={()=>setUploadOpen(true)}><UploadCloud size={17}/> آپلود فایل</Button></>} />
    <AdminCard className="admin-toolbar"><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="جست‌وجوی عنوان، فایل یا منبع…"/><Select value={mediaType} onChange={e=>setMediaType(e.target.value)}><option value="">همه نوع‌ها</option><option value="image">تصویر</option><option value="infographic">اینفوگرافیک</option><option value="document">فایل/سند</option><option value="video">ویدئو</option><option value="audio">صوت</option></Select><Select value={status} onChange={e=>setStatus(e.target.value)}><option value="">همه وضعیت‌ها</option><option value="approved">تأییدشده</option><option value="source_review_required">بررسی منبع</option><option value="file_license_review_required">بررسی مجوز فایل</option><option value="reference_only">فقط مرجع</option></Select><Button variant="outline" onClick={()=>query.refetch()}><RefreshCw size={17}/> بروزرسانی</Button></AdminCard>
    {query.isError?<AdminError message="کتابخانه رسانه دریافت نشد."/>:null}{error?<AdminError message={error.message}/>:null}
    <div className="admin-media-grid">{query.data?.items.map(item=><AdminCard key={item.id} className="admin-media-card"><div className="admin-media-preview">{item.media_type==="image"&&item.asset_url?<img src={resolveMediaUrl(item.thumbnail_url||item.asset_url)} alt={item.alt_text||item.title}/>:item.media_type==="image"?<FileImage size={34}/>:<File size={34}/>}</div><div className="admin-media-copy"><div><strong>{item.title}</strong><AdminStatus value={item.review_status}/></div><small>{item.original_file_name||item.source_name||item.media_type}</small><p>{item.alt_text||"بدون متن جایگزین"}</p><div className="admin-media-meta"><span>{formatBytes(item.size_bytes)}</span><span>{formatAdminDate(item.updated_at)}</span></div></div><footer><Button variant="outline" onClick={()=>openEdit(item)}><Pencil size={15}/> ویرایش</Button><Button variant="ghost" onClick={()=>{if(window.confirm("این رسانه حذف شود؟"))remove.mutate(item.id)}}><Trash2 size={15}/></Button></footer></AdminCard>)}</div>
    {!query.isLoading&&!query.data?.items.length?<AdminCard><AdminEmpty title="رسانه‌ای پیدا نشد" description="فایل آپلود کنید یا یک رسانه خارجی با منبع و مجوز ثبت کنید."/></AdminCard>:null}

    {uploadOpen?<AdminModal title="آپلود تصویر یا فایل" description="حداکثر ۲۰ مگابایت. HTML، SVG و فایل اجرایی پذیرفته نمی‌شود." onClose={()=>setUploadOpen(false)} footer={<><Button variant="outline" onClick={()=>setUploadOpen(false)}>انصراف</Button><Button disabled={!file||!uploadForm.rights_confirmed||upload.isPending} onClick={()=>upload.mutate()}>{upload.isPending?"در حال آپلود…":"آپلود و ثبت"}</Button></>}><div className="admin-form-grid"><Field label="فایل"><label className="admin-file-drop"><input type="file" accept="image/jpeg,image/png,image/webp,image/gif,application/pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.txt,.csv" onChange={e=>setFile(e.target.files?.[0])}/><UploadCloud size={28}/><strong>{file?.name||"انتخاب فایل"}</strong><small>{file?formatBytes(file.size):"تصویر، PDF و فایل‌های اداری"}</small></label></Field><Field label="اتصال به مطلب"><Select value={uploadForm.content_id} onChange={e=>setUploadForm({...uploadForm,content_id:e.target.value})}><option value="">بدون مطلب</option>{contents.data?.items.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</Select></Field><Field label="عنوان"><Input value={uploadForm.title} onChange={e=>setUploadForm({...uploadForm,title:e.target.value})} placeholder="در صورت خالی بودن از نام فایل استفاده می‌شود"/></Field><Field label="متن جایگزین تصویر"><Input value={uploadForm.alt_text} onChange={e=>setUploadForm({...uploadForm,alt_text:e.target.value})}/></Field><label className="admin-check admin-span-2"><input type="checkbox" checked={uploadForm.rights_confirmed} onChange={e=>setUploadForm({...uploadForm,rights_confirmed:e.target.checked})}/><span><strong>حق انتشار این فایل را تأیید می‌کنم</strong><small>فقط فایل متعلق به نینیبو یا دارای مجوز مناسب برای استفاده تجاری آپلود شود.</small></span></label></div></AdminModal>:null}
    {(externalOpen||editing)?<AdminModal title={editing?"ویرایش رسانه":"رسانه خارجی"} description="برای رسانه‌های خارج از storage نینیبو، URL، منبع و مجوز را دقیق ثبت کنید." onClose={()=>{setExternalOpen(false);setEditing(undefined);setExternal(blankExternal)}} footer={<><Button variant="outline" onClick={()=>{setExternalOpen(false);setEditing(undefined);setExternal(blankExternal)}}>انصراف</Button><Button disabled={!external.title.trim()||!(external.asset_url.trim()||editing?.storage_key)||(editing?update.isPending:create.isPending)} onClick={()=>editing?update.mutate():create.mutate()}>{editing?"ذخیره تغییرات":"ثبت رسانه"}</Button></>}><ExternalMediaFields value={external} onChange={setExternal} contents={contents.data?.items||[]} lockedAsset={Boolean(editing?.storage_key)}/></AdminModal>:null}
  </div>;
}

function ExternalMediaFields({value,onChange,contents,lockedAsset}:{value:ExternalForm;onChange:(v:ExternalForm)=>void;contents:AdminKnowledgeList["items"];lockedAsset:boolean}){return <div className="admin-form-grid"><Field label="نوع"><Select value={value.media_type} onChange={e=>onChange({...value,media_type:e.target.value})}><option value="image">تصویر</option><option value="infographic">اینفوگرافیک</option><option value="document">سند</option><option value="video">ویدئو</option><option value="audio">صوت</option></Select></Field><Field label="مطلب مرتبط"><Select value={value.content_id} onChange={e=>onChange({...value,content_id:e.target.value})}><option value="">بدون مطلب</option>{contents.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</Select></Field><Field label="عنوان"><Input value={value.title} onChange={e=>onChange({...value,title:e.target.value})}/></Field><Field label="Alt text"><Input value={value.alt_text} onChange={e=>onChange({...value,alt_text:e.target.value})}/></Field><Field label="URL فایل"><Input dir="ltr" disabled={lockedAsset} value={value.asset_url} onChange={e=>onChange({...value,asset_url:e.target.value})}/></Field><Field label="URL بندانگشتی"><Input dir="ltr" value={value.thumbnail_url} onChange={e=>onChange({...value,thumbnail_url:e.target.value})}/></Field><Field label="منبع"><Input value={value.source_name} onChange={e=>onChange({...value,source_name:e.target.value})}/></Field><Field label="URL منبع"><Input dir="ltr" value={value.source_url} onChange={e=>onChange({...value,source_url:e.target.value})}/></Field><Field label="پدیدآورنده"><Input value={value.author} onChange={e=>onChange({...value,author:e.target.value})}/></Field><Field label="کد مجوز"><Input value={value.license_code} onChange={e=>onChange({...value,license_code:e.target.value})}/></Field><Field label="URL مجوز"><Input dir="ltr" value={value.license_url} onChange={e=>onChange({...value,license_url:e.target.value})}/></Field><Field label="متن attribution"><Input value={value.attribution_text} onChange={e=>onChange({...value,attribution_text:e.target.value})}/></Field><Field label="وضعیت بررسی"><Select value={value.review_status} onChange={e=>onChange({...value,review_status:e.target.value})}><option value="source_review_required">بررسی منبع</option><option value="file_license_review_required">بررسی مجوز فایل</option><option value="reference_only">فقط مرجع</option><option value="approved">تأییدشده</option></Select></Field><div className="admin-inline-checks"><label><input type="checkbox" checked={value.commercial_use_allowed} onChange={e=>onChange({...value,commercial_use_allowed:e.target.checked})}/> استفاده تجاری مجاز</label><label><input type="checkbox" checked={value.derivative_allowed} onChange={e=>onChange({...value,derivative_allowed:e.target.checked})}/> تغییر اثر مجاز</label></div></div>}
function mediaPayload(v:ExternalForm){return {...v,content_id:v.content_id?Number(v.content_id):null,metadata:{managed_from:"admin_panel"}}}
function formatBytes(value?:number){if(!value)return "—";if(value<1024)return `${value} B`;if(value<1024*1024)return `${(value/1024).toFixed(1)} KB`;return `${(value/1024/1024).toFixed(1)} MB`}
