"use client";
import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BadgeCheck, Search, Store, Stethoscope } from "lucide-react";
import type { AdminProvider, AdminProviderList } from "@ninibu/types";
import { clientApi } from "@/lib/client-api";
import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Select } from "@/components/ui/select"; import { Field } from "@/components/ui/field"; import { Textarea } from "@/components/ui/textarea";
import { AdminCard, AdminEmpty, AdminError, AdminModal, AdminPageHeader, AdminStatus, formatAdminDate } from "@/components/admin/common";

export function AdminProvidersPanel(){const qc=useQueryClient(); const [search,setSearch]=useState(""); const [kind,setKind]=useState(""); const [status,setStatus]=useState(""); const [selected,setSelected]=useState<AdminProvider>(); const qs=useMemo(()=>new URLSearchParams({limit:"100",...(search?{search}:{}),...(kind?{provider_type:kind}:{}),...(status?{status}:{})}).toString(),[search,kind,status]); const q=useQuery({queryKey:["admin","providers",qs],queryFn:()=>clientApi<AdminProviderList>(`/api/ninibu/admin/backoffice/providers?${qs}`)}); const invalidate=()=>qc.invalidateQueries({queryKey:["admin","providers"]}); return <div className="admin-page"><AdminPageHeader eyebrow="Provider Governance" title="مدیریت ارائه‌دهندگان" description="تأیید و تعلیق متخصصان، مشاوران، مدرس‌ها و فروشندگان. دسترسی بالینی همچنان تابع مجوز مستقل پرونده کودک است."/><AdminCard className="admin-toolbar"><div className="admin-search-field"><Search size={17}/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="نام، موبایل یا دسته…"/></div><Select value={kind} onChange={e=>setKind(e.target.value)}><option value="">همه ارائه‌دهندگان</option><option value="clinician">پزشک/متخصص</option><option value="seller">فروشنده/ارائه‌دهنده</option></Select><Select value={status} onChange={e=>setStatus(e.target.value)}><option value="">همه وضعیت‌ها</option><option value="pending">در انتظار</option><option value="verified">تأییدشده</option><option value="rejected">ردشده</option><option value="suspended">تعلیق</option></Select></AdminCard>{q.isError?<AdminError message="فهرست ارائه‌دهندگان دریافت نشد."/>:null}<AdminCard className="admin-table-card"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>ارائه‌دهنده</th><th>نوع</th><th>دسته</th><th>تأیید</th><th>عملیاتی</th><th>ثبت</th><th>عملیات</th></tr></thead><tbody>{q.data?.items.map(x=><tr key={`${x.provider_type}-${x.provider_id}`}><td><strong>{x.name||"بدون نام"}</strong><small dir="ltr">{x.mobile}</small></td><td>{x.provider_type==="clinician"?<span className="admin-provider-type"><Stethoscope size={15}/>متخصص</span>:<span className="admin-provider-type"><Store size={15}/>Provider</span>}</td><td>{x.category||"—"}</td><td><AdminStatus value={x.verification_status}/></td><td><AdminStatus value={x.operational_status}/></td><td>{formatAdminDate(x.created_at)}</td><td><Button variant="outline" onClick={()=>setSelected(x)}><BadgeCheck size={16}/> بررسی</Button></td></tr>)}</tbody></table></div>{!q.isLoading&&!q.data?.items.length?<AdminEmpty title="ارائه‌دهنده‌ای پیدا نشد" description="فیلترهای جست‌وجو را تغییر دهید."/>:null}</AdminCard>{selected?<ProviderAction provider={selected} onClose={()=>setSelected(undefined)} onSaved={()=>{setSelected(undefined);void invalidate();}}/>:null}</div>}
function ProviderAction({provider,onClose,onSaved}:{provider:AdminProvider;onClose:()=>void;onSaved:()=>void}){const [status,setStatus]=useState<"verified"|"rejected"|"suspended">("verified");const [note,setNote]=useState("");const [cats,setCats]=useState("");const m=useMutation({mutationFn:()=>provider.provider_type==="clinician"?clientApi(`/api/ninibu/admin/clinicians/${provider.provider_id}/verification`,{method:"PATCH",body:JSON.stringify({status,note,consultation_category_codes:cats.split(",").map(x=>x.trim()).filter(Boolean)})}):clientApi(`/api/ninibu/admin/commerce/sellers/${provider.provider_id}/${status==="verified"?"verify":status==="rejected"?"reject":"suspend"}`,{method:"POST",body:JSON.stringify(status==="verified"?{}:{reason:note})}),onSuccess:onSaved});return <AdminModal title={`بررسی ${provider.name}`} description={`${provider.provider_type} #${provider.provider_id}`} onClose={onClose} footer={<><Button variant="outline" onClick={onClose}>انصراف</Button><Button disabled={m.isPending||(status!=="verified"&&note.trim().length<3)} onClick={()=>m.mutate()}>ثبت تصمیم</Button></>}><div className="admin-form-grid"><Field label="تصمیم"><Select value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="verified">تأیید</option><option value="rejected">رد</option><option value="suspended">تعلیق</option></Select></Field>{provider.provider_type==="clinician"&&status==="verified"?<Field label="کد دسته‌های مشاوره" hint="با کاما جدا کنید؛ در اولین تأیید متخصص ممکن است لازم باشد"><Input dir="ltr" value={cats} onChange={e=>setCats(e.target.value)} placeholder="pediatrics,nutrition"/></Field>:null}<Field label="یادداشت / دلیل"><Textarea value={note} onChange={e=>setNote(e.target.value)}/></Field>{m.error?<AdminError message={(m.error as Error).message}/>:null}</div></AdminModal>}
