import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import Ionicons from '@expo/vector-icons/Ionicons';
import type { CommunityComment, CommunityCommentListResponse, CommunityPost, CommunityPrivacyMode, CommunityReactionType, CommunityReportReason } from '@ninibu/types';
import { formatRelativeFa, toPersianDigits } from '@ninibu/datetime';
import { api, apiPaths } from '@/lib/api';
import { Badge, Button, Card, ChoiceModal, EmptyState, ErrorState, Field, FormModal, Header, IconButton, Loading, Screen, SectionTitle, SegmentedControl, SelectField } from '@/components/ui';
import { colors, typography } from '@/theme';

const reactions: Array<{ type: CommunityReactionType; label: string }> = [
  { type: 'like', label: 'پسند' }, { type: 'helpful', label: 'مفید' }, { type: 'support', label: 'همراهی' }, { type: 'thanks', label: 'سپاس' },
];
const reportReasons: Array<{ id: number; value: CommunityReportReason; label: string }> = [
  { id: 1, value: 'medical_misinformation', label: 'اطلاعات پزشکی نادرست' }, { id: 2, value: 'dangerous_advice', label: 'توصیه خطرناک' }, { id: 3, value: 'harassment', label: 'آزار یا توهین' }, { id: 4, value: 'spam', label: 'اسپم' }, { id: 5, value: 'advertising', label: 'تبلیغ نامرتبط' }, { id: 6, value: 'privacy_violation', label: 'نقض حریم خصوصی' }, { id: 7, value: 'inappropriate_content', label: 'محتوای نامناسب' }, { id: 8, value: 'other', label: 'سایر' },
];

export default function CommunityPostDetail() {
  const { postId } = useLocalSearchParams<{ postId: string }>(); const id = Number(postId);
  const [post, setPost] = useState<CommunityPost>(); const [comments, setComments] = useState<CommunityCommentListResponse>(); const [body, setBody] = useState(''); const [privacy, setPrivacy] = useState<CommunityPrivacyMode>('identified'); const [replyTo, setReplyTo] = useState<CommunityComment>(); const [loadingPost, setLoadingPost] = useState(true); const [loadingComments, setLoadingComments] = useState(true); const [sending, setSending] = useState(false); const [busyReaction, setBusyReaction] = useState(false); const [postError, setPostError] = useState(''); const [commentsError, setCommentsError] = useState(''); const [sendError, setSendError] = useState(''); const [reportTarget, setReportTarget] = useState<{ type: 'community_post' | 'community_comment'; id: number }>();

  async function loadPost() { if (!id) return; setLoadingPost(true); setPostError(''); try { setPost(await api<CommunityPost>(apiPaths.communityPost(id))); } catch (cause) { setPostError(cause instanceof Error ? cause.message : 'پست دریافت نشد.'); } finally { setLoadingPost(false); } }
  async function loadComments() { if (!id) return; setLoadingComments(true); setCommentsError(''); try { setComments(await api<CommunityCommentListResponse>(`${apiPaths.communityPostComments(id)}?limit=100`)); } catch (cause) { setCommentsError(cause instanceof Error ? cause.message : 'دیدگاه‌ها دریافت نشدند.'); } finally { setLoadingComments(false); } }
  async function refreshAll() { await Promise.all([loadPost(), loadComments()]); }
  useEffect(() => { void refreshAll(); }, [id]);

  async function send() { if (!body.trim() || !post) return; setSending(true); setSendError(''); try { await api(apiPaths.communityPostComments(post.id), { method: 'POST', body: JSON.stringify({ body: body.trim(), privacy_mode: privacy, parent_comment_id: replyTo?.id }) }); setBody(''); setReplyTo(undefined); await refreshAll(); } catch (cause) { setSendError(cause instanceof Error ? cause.message : 'ثبت دیدگاه انجام نشد.'); } finally { setSending(false); } }
  async function reactPost(type: CommunityReactionType) { if (!post) return; const active = post.reactions?.find((r) => r.reaction_type === type)?.reacted_by_me; setBusyReaction(true); try { if (active) await api(apiPaths.communityPostReaction(post.id, type), { method: 'DELETE' }); else await api(apiPaths.communityPostReactions(post.id), { method: 'POST', body: JSON.stringify({ reaction_type: type }) }); await loadPost(); } finally { setBusyReaction(false); } }
  async function reactComment(comment: CommunityComment, type: CommunityReactionType) { const active = comment.reactions?.find((r) => r.reaction_type === type)?.reacted_by_me; setBusyReaction(true); try { if (active) await api(apiPaths.communityCommentReaction(comment.id, type), { method: 'DELETE' }); else await api(apiPaths.communityCommentReactions(comment.id), { method: 'POST', body: JSON.stringify({ reaction_type: type }) }); await loadComments(); } finally { setBusyReaction(false); } }

  return <Screen refreshing={loadingPost || loadingComments} onRefresh={refreshAll}>
    <Header title="گفت‌وگو" subtitle={post?.group_name || 'جامعه نینیبو'} right={<IconButton icon="arrow-forward" label="بازگشت" onPress={() => router.back()} />} />
    {postError ? <ErrorState message={postError} onRetry={loadPost} /> : loadingPost ? <Loading label="در حال دریافت پست…" /> : post ? <>
      <Card>
        <View style={styles.authorRow}><View style={styles.avatar}><Ionicons name={post.author.author_type === 'verified_clinician' ? 'medkit' : 'person'} size={17} color={colors.primary} /></View><View style={{ flex: 1 }}><Text style={styles.author}>{post.author.display_name}</Text><Text style={styles.meta}>{formatRelativeFa(post.published_at)}</Text></View><Pressable onPress={() => setReportTarget({ type: 'community_post', id: post.id })}><Ionicons name="flag-outline" size={18} color={colors.muted} /></Pressable></View>
        {post.title ? <Text style={styles.title}>{post.title}</Text> : null}<Text style={styles.body}>{post.body}</Text>{post.medical_disclaimer ? <Text style={styles.disclaimer}>{post.medical_disclaimer}</Text> : null}
        <View style={styles.reactions}>{reactions.map((item) => { const r = post.reactions?.find((x) => x.reaction_type === item.type); return <Pressable key={item.type} disabled={busyReaction} onPress={() => void reactPost(item.type)} style={[styles.reactionBtn, r?.reacted_by_me && styles.reactionActive]}><Text style={[styles.reactionText, r?.reacted_by_me && styles.reactionTextActive]}>{item.label}{r?.count ? ` ${toPersianDigits(r.count)}` : ''}</Text></Pressable>; })}</View>
      </Card>
      <SectionTitle title="دیدگاه‌ها" />
      {commentsError ? <ErrorState message={commentsError} onRetry={loadComments} /> : loadingComments ? <Loading label="در حال دریافت دیدگاه‌ها…" /> : comments?.items.length ? comments.items.map((comment) => <Card key={comment.id} style={[styles.commentCard, comment.depth > 0 && styles.replyCard]}>
        <View style={styles.commentHead}><View style={{ flex: 1 }}><Text style={styles.author}>{comment.author.display_name}</Text><Text style={styles.meta}>{formatRelativeFa(comment.created_at)}</Text></View>{comment.author.author_type === 'verified_clinician' ? <Badge tone="green">متخصص</Badge> : comment.author.is_mine ? <Badge tone="purple">شما</Badge> : null}<Pressable onPress={() => setReportTarget({ type: 'community_comment', id: comment.id })}><Ionicons name="flag-outline" size={16} color={colors.muted} /></Pressable></View>
        <Text style={styles.body}>{comment.body}</Text><View style={styles.commentActions}>{reactions.slice(1).map((item) => { const r = comment.reactions?.find((x) => x.reaction_type === item.type); return <Pressable key={item.type} disabled={busyReaction} onPress={() => void reactComment(comment, item.type)}><Text style={[styles.commentActionText, r?.reacted_by_me && styles.reactionTextActive]}>{item.label}{r?.count ? ` ${toPersianDigits(r.count)}` : ''}</Text></Pressable>; })}{comment.depth === 0 ? <Pressable onPress={() => setReplyTo(comment)}><Text style={styles.commentActionText}>پاسخ</Text></Pressable> : null}</View>
      </Card>) : <EmptyState title="هنوز دیدگاهی ثبت نشده" text="اولین دیدگاه را شما ثبت کنید." />}
      {!post.is_locked ? <Card style={styles.composer}>{replyTo ? <View style={styles.replyBanner}><Text style={styles.replyText}>پاسخ به {replyTo.author.display_name}</Text><Pressable onPress={() => setReplyTo(undefined)}><Ionicons name="close" size={18} color={colors.muted} /></Pressable></View> : null}<SegmentedControl<CommunityPrivacyMode> value={privacy} onChange={setPrivacy} items={[{ value: 'identified', label: 'با نام' }, { value: 'anonymous', label: 'ناشناس' }]} /><Field label="متن دیدگاه" value={body} onChangeText={setBody} multiline maxLength={5000} placeholder="تجربه یا نظر خود را بنویسید…" />{sendError ? <Text style={styles.sendError}>{sendError}</Text> : null}<Button title="ثبت دیدگاه" icon="send" loading={sending} disabled={!body.trim()} onPress={send} /></Card> : null}
    </> : <EmptyState title="پست پیدا نشد" />}
    <ReportModal target={reportTarget} onClose={() => setReportTarget(undefined)} />
  </Screen>;
}

function ReportModal({ target, onClose }: { target?: { type: 'community_post' | 'community_comment'; id: number }; onClose: () => void }) { const [reason, setReason] = useState(reportReasons[0]); const [picker, setPicker] = useState(false); const [description, setDescription] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); async function submit() { if (!target) return; setBusy(true); setError(''); try { await api(apiPaths.communityReports, { method: 'POST', body: JSON.stringify({ entity_type: target.type, entity_id: target.id, reason: reason.value, description: description.trim() }) }); onClose(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'ارسال گزارش انجام نشد.'); } finally { setBusy(false); } } return <><FormModal visible={!!target} title="گزارش محتوا" onClose={onClose}><SelectField label="دلیل گزارش" value={reason.label} placeholder="انتخاب دلیل" onPress={() => setPicker(true)} /><Field label="توضیح اختیاری" value={description} onChangeText={setDescription} multiline />{error ? <Text style={styles.sendError}>{error}</Text> : null}<Button title="ارسال گزارش" loading={busy} onPress={submit} /></FormModal><ChoiceModal visible={picker} title="دلیل گزارش" items={reportReasons} label={(item) => item.label} onChoose={setReason} onClose={() => setPicker(false)} /></>; }

const styles = StyleSheet.create({ authorRow: { flexDirection: 'row-reverse', alignItems: 'center', gap: 10 }, commentHead: { flexDirection: 'row-reverse', justifyContent: 'space-between', alignItems: 'center', gap: 10 }, avatar: { width: 38, height: 38, borderRadius: 13, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, author: { fontFamily: typography.bold, fontSize: 12.5, fontWeight: '900', textAlign: 'right', writingDirection: 'rtl' }, meta: { fontFamily: typography.regular, fontSize: 9.5, color: colors.muted, textAlign: 'right', writingDirection: 'rtl', marginTop: 3 }, title: { fontFamily: typography.bold, fontSize: 17, fontWeight: '900', textAlign: 'right', writingDirection: 'rtl', marginTop: 13 }, body: { fontFamily: typography.regular, fontSize: 12.5, color: colors.foreground, textAlign: 'right', writingDirection: 'rtl', lineHeight: 23, marginTop: 8 }, disclaimer: { fontFamily: typography.regular, fontSize: 10, color: colors.warning, textAlign: 'right', writingDirection: 'rtl', lineHeight: 19, marginTop: 10 }, reactions: { flexDirection: 'row-reverse', gap: 5, flexWrap: 'wrap', marginTop: 12 }, reactionBtn: { paddingHorizontal: 9, paddingVertical: 7, borderRadius: 999, borderWidth: 1, borderColor: colors.border }, reactionActive: { backgroundColor: colors.primarySoft, borderColor: '#D5CBF5' }, reactionText: { fontFamily: typography.regular, fontSize: 9.5, color: colors.muted }, reactionTextActive: { fontFamily: typography.bold, color: colors.primaryStrong, fontWeight: '900' }, commentCard: { gap: 2 }, replyCard: { marginRight: 20, borderRightWidth: 3, borderRightColor: '#D9D1F4' }, commentActions: { flexDirection: 'row-reverse', gap: 14, marginTop: 10 }, commentActionText: { fontFamily: typography.bold, fontSize: 10, color: colors.primaryStrong, fontWeight: '800' }, composer: { gap: 12 }, replyBanner: { flexDirection: 'row-reverse', justifyContent: 'space-between', alignItems: 'center', padding: 10, backgroundColor: colors.primarySoft, borderRadius: 13 }, replyText: { fontFamily: typography.regular, fontSize: 10.5, color: colors.primaryStrong, writingDirection: 'rtl' }, sendError: { fontFamily: typography.regular, fontSize: 10.5, color: colors.danger, textAlign: 'right', writingDirection: 'rtl', backgroundColor: colors.dangerSoft, borderRadius: 12, padding: 9 } });
