import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import Ionicons from '@expo/vector-icons/Ionicons';
import type { CommunityCommentListResponse, CommunityPost } from '@ninibu/types';
import { formatRelativeFa, toPersianDigits } from '@ninibu/datetime';
import { api, apiPaths } from '@/lib/api';
import { Badge, Button, Card, EmptyState, ErrorState, Field, Header, IconButton, Loading, Screen, SectionTitle } from '@/components/ui';
import { colors } from '@/theme';

export default function CommunityPostDetail(){
  const {postId}=useLocalSearchParams<{postId:string}>(); const id=Number(postId);
  const [post,setPost]=useState<CommunityPost>(); const [comments,setComments]=useState<CommunityCommentListResponse>();
  const [body,setBody]=useState(''); const [loading,setLoading]=useState(true); const [sending,setSending]=useState(false); const [error,setError]=useState('');
  async function load(){if(!id)return;setLoading(true);setError('');try{const [p,c]=await Promise.all([api<CommunityPost>(apiPaths.communityPost(id)),api<CommunityCommentListResponse>(`${apiPaths.communityPostComments(id)}?limit=100`)]);setPost(p);setComments(c)}catch(e){setError(e instanceof Error?e.message:'خطا در دریافت پست')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[id]);
  async function send(){if(!body.trim()||!post)return;setSending(true);setError('');try{await api(apiPaths.communityPostComments(post.id),{method:'POST',body:JSON.stringify({body:body.trim(),privacy_mode:'identified'})});setBody('');await load()}catch(e){setError(e instanceof Error?e.message:'ثبت دیدگاه انجام نشد')}finally{setSending(false)}}
  return <Screen refreshing={loading} onRefresh={load}><Header title="گفت‌وگو" subtitle={post?.group_name||'جامعه نینیبو'} right={<IconButton icon="arrow-forward" label="بازگشت" onPress={()=>router.back()}/>}/>{error?<ErrorState message={error} onRetry={load}/>:loading?<Loading/>:post?<><Card><View style={s.authorRow}><View style={s.avatar}><Ionicons name={post.author.author_type==='verified_clinician'?'medkit':'person'} size={17} color={colors.primary}/></View><View style={{flex:1}}><Text style={s.author}>{post.author.display_name}</Text><Text style={s.meta}>{formatRelativeFa(post.published_at)}</Text></View>{post.author.author_type==='verified_clinician'?<Badge tone="green">متخصص تأییدشده</Badge>:null}</View>{post.title?<Text style={s.title}>{post.title}</Text>:null}<Text style={s.body}>{post.body}</Text>{post.medical_disclaimer?<Text style={s.disclaimer}>{post.medical_disclaimer}</Text>:null}<Text style={s.stats}>💬 {toPersianDigits(post.comment_count)} دیدگاه · ♡ {toPersianDigits(post.reaction_count)}</Text></Card><SectionTitle kicker="گفت‌وگو" title="دیدگاه‌ها"/>{comments?.items.length?comments.items.map(c=><Card key={c.id}><View style={s.commentHead}><Text style={s.author}>{c.author.display_name}</Text>{c.author.author_type==='verified_clinician'?<Badge tone="green">متخصص</Badge>:null}</View><Text style={s.body}>{c.body}</Text><Text style={s.meta}>{formatRelativeFa(c.created_at)}</Text></Card>):<EmptyState title="هنوز دیدگاهی ثبت نشده" text="اولین دیدگاه را شما ثبت کنید."/>}{!post.is_locked?<Card><Field label="دیدگاه شما" value={body} onChangeText={setBody} multiline placeholder="تجربه یا نظر خود را بنویسید…"/><Button title="ثبت دیدگاه" icon="send" loading={sending} disabled={!body.trim()} onPress={send}/></Card>:<Card><Text style={s.disclaimer}>این پست برای دیدگاه جدید قفل شده است.</Text></Card>}</>:<EmptyState title="پست پیدا نشد"/>}</Screen>
}
const s=StyleSheet.create({authorRow:{flexDirection:'row-reverse',alignItems:'center',gap:10},commentHead:{flexDirection:'row-reverse',justifyContent:'space-between',alignItems:'center'},avatar:{width:38,height:38,borderRadius:13,backgroundColor:colors.primarySoft,alignItems:'center',justifyContent:'center'},author:{fontSize:13,fontWeight:'900',textAlign:'right',writingDirection:'rtl'},meta:{fontSize:10.5,color:colors.muted,textAlign:'right',writingDirection:'rtl',marginTop:3},title:{fontSize:18,fontWeight:'900',textAlign:'right',writingDirection:'rtl',marginTop:14},body:{fontSize:13,color:colors.foreground,textAlign:'right',writingDirection:'rtl',lineHeight:23,marginTop:9},disclaimer:{fontSize:10.5,color:colors.warning,textAlign:'right',writingDirection:'rtl',lineHeight:19,marginTop:10},stats:{fontSize:11,color:colors.muted,textAlign:'right',writingDirection:'rtl',marginTop:12}})
