import { useEffect, useMemo, useState } from 'react';
import { Image, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { normalizeIranMobile, passwordSchema } from '@ninibu/validation';
import { Button, Card, Field } from '@/components/ui';
import { ApiError, forgotRequestOtp, login, resetPassword, signup, signupRequestOtp } from '@/lib/api';
import { useSession } from '@/providers/SessionProvider';
import { colors } from '@/theme';

type Mode='login'|'signup'|'forgot';
function validMobile(v:string){return /^\+989\d{9}$/.test(v)}
export default function AuthScreen(){
 const session=useSession();const [mode,setMode]=useState<Mode>('login');const [mobile,setMobile]=useState('');const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [code,setCode]=useState('');const [otp,setOtp]=useState(false);const [retry,setRetry]=useState(0);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [info,setInfo]=useState('');
 useEffect(()=>{if(retry<=0)return;const t=setInterval(()=>setRetry(v=>Math.max(0,v-1)),1000);return()=>clearInterval(t)},[retry]);
 const copy=useMemo(()=>mode==='login'?['به نینیبو خوش آمدید','برای ورود روزمره شماره موبایل و رمز عبور کافی است.']:mode==='signup'?(otp?['تأیید شماره و ساخت حساب','کد پیامک‌شده را وارد کنید.']:['ساخت حساب نینیبو','رمز عبور را تعریف کنید؛ پیامک فقط برای تأیید ثبت‌نام است.']):(otp?['تأیید و تغییر رمز','کد بازیابی را وارد کنید.']:['بازیابی رمز عبور','رمز جدید را تعریف کنید و مالکیت شماره را با پیامک تأیید کنید.']),[mode,otp]);
 function switchMode(m:Mode){setMode(m);setOtp(false);setCode('');setConfirm('');setError('');setInfo('');setRetry(0)}
 function normalized(){const n=normalizeIranMobile(mobile);if(!validMobile(n))throw new Error('شماره موبایل معتبر وارد کنید.');setMobile(n);return n}
 function validatePassword(){const r=passwordSchema.safeParse(password);if(!r.success)throw new Error(r.error.issues[0]?.message||'رمز عبور معتبر نیست.');if(password!==confirm)throw new Error('تکرار رمز عبور با رمز جدید یکسان نیست.')}
 async function done(){await session.signedIn()}
 async function doLogin(){setLoading(true);setError('');setInfo('');try{const m=normalized();if(!password)throw new Error('رمز عبور را وارد کنید.');await login(m,password);await done()}catch(e){if(e instanceof ApiError&&e.code==='PASSWORD_SETUP_REQUIRED'){switchMode('forgot');setInfo('این حساب از نسخه قبلی منتقل شده و هنوز رمز عبور ندارد. یک رمز جدید تعریف کنید.')}else if(e instanceof ApiError&&e.code==='INVALID_CREDENTIALS')setError('شماره موبایل یا رمز عبور صحیح نیست.');else setError(e instanceof Error?e.message:'ورود ناموفق بود.')}finally{setLoading(false)}}
 async function request(){setLoading(true);setError('');setInfo('');try{const m=normalized();validatePassword();const r=mode==='signup'?await signupRequestOtp(m,password):await forgotRequestOtp(m,password);setOtp(true);setRetry(r.retry_after??60);if(r.debug_code)setCode(r.debug_code)}catch(e){if(e instanceof ApiError&&e.code==='ACCOUNT_EXISTS'){switchMode('login');setError('این شماره قبلاً ثبت‌نام کرده است. با رمز عبور وارد شوید.')}else setError(e instanceof Error?e.message:'ارسال کد ناموفق بود.')}finally{setLoading(false)}}
 async function verify(){setLoading(true);setError('');try{const m=normalized();validatePassword();if(!/^\d{6}$/.test(code))throw new Error('کد تأیید ۶ رقمی را وارد کنید.');if(mode==='signup')await signup(m,password,code);else await resetPassword(m,password,code);await done()}catch(e){setError(e instanceof Error?e.message:'تأیید کد ناموفق بود.')}finally{setLoading(false)}}
 return <LinearGradient colors={['#FFF0F5','#F8F7FB','#F0EEFF']} style={{flex:1}}><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={{flex:1}}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.stage}><Image source={require('../../assets/ninibu-logo.png')} style={s.logo}/><Card style={s.card}><View><Text style={s.title}>{copy[0]}</Text><Text style={s.copy}>{copy[1]}</Text></View><Field label="شماره موبایل" value={mobile} onChangeText={setMobile} placeholder="0912 123 4567" keyboardType="phone-pad" editable={!otp}/><Field label={mode==='forgot'?'رمز عبور جدید':'رمز عبور'} hint={mode==='login'?undefined:'حداقل ۸ کاراکتر'} value={password} onChangeText={setPassword} secure editable={!otp}/>{mode!=='login'?<Field label="تکرار رمز عبور" value={confirm} onChangeText={setConfirm} secure editable={!otp}/>:null}{otp?<Field label="کد تأیید" value={code} onChangeText={v=>setCode(v.replace(/\D/g,'').slice(0,6))} keyboardType="number-pad"/>:null}{info?<Text style={s.info}>{info}</Text>:null}{error?<Text style={s.error}>{error}</Text>:null}{mode==='login'?<><Button title="ورود با رمز عبور" onPress={doLogin} loading={loading}/><View style={s.links}><Pressable onPress={()=>switchMode('forgot')}><Text style={s.link}>رمز عبور را فراموش کرده‌ام</Text></Pressable><Pressable onPress={()=>switchMode('signup')}><Text style={s.linkStrong}>ثبت‌نام برای اولین بار</Text></Pressable></View></>:!otp?<><Button title={mode==='signup'?'ارسال کد ثبت‌نام':'ارسال کد بازیابی'} onPress={request} loading={loading}/><Button title="بازگشت به ورود" variant="ghost" onPress={()=>switchMode('login')}/></>:<><Button title={mode==='signup'?'تأیید و ساخت حساب':'تأیید و تغییر رمز'} onPress={verify} loading={loading}/><View style={s.links}><Pressable disabled={retry>0} onPress={request}><Text style={[s.link,retry>0&&{opacity:.5}]}>{retry>0?`ارسال مجدد تا ${new Intl.NumberFormat('fa-IR').format(retry)} ثانیه`:'ارسال مجدد کد'}</Text></Pressable><Pressable onPress={()=>{setOtp(false);setRetry(0);setCode('')}}><Text style={s.linkStrong}>ویرایش اطلاعات</Text></Pressable></View></>}</Card><Text style={s.footer}>نینیبو · همراه والدین برای رشد، سلامت و تجربه بهتر خانواده</Text></ScrollView></KeyboardAvoidingView></LinearGradient>
}
const s=StyleSheet.create({stage:{flexGrow:1,justifyContent:'center',padding:20,gap:14},logo:{width:190,height:90,resizeMode:'contain',alignSelf:'center'},card:{gap:17},title:{fontSize:24,fontWeight:'900',color:colors.foreground,textAlign:'right',writingDirection:'rtl'},copy:{fontSize:12.5,lineHeight:21,color:colors.muted,textAlign:'right',writingDirection:'rtl',marginTop:6},links:{gap:13,alignItems:'center',paddingTop:2},link:{fontSize:12,color:colors.primary,writingDirection:'rtl'},linkStrong:{fontSize:12,fontWeight:'900',color:colors.primaryStrong,writingDirection:'rtl'},error:{fontSize:11.5,color:colors.danger,textAlign:'right',writingDirection:'rtl',backgroundColor:colors.dangerSoft,padding:10,borderRadius:12},info:{fontSize:11.5,color:colors.primaryStrong,textAlign:'right',writingDirection:'rtl',backgroundColor:colors.primarySoft,padding:10,borderRadius:12},footer:{fontSize:10.5,color:colors.muted,textAlign:'center',writingDirection:'rtl',marginTop:5}})
