import type { Href } from 'expo-router';

/**
 * Expo Router typed-route declarations are generated by the Expo CLI and may
 * be absent/stale before Metro has started. Keep application navigation typed
 * at the boundary without making plain `tsc --noEmit` depend on generated
 * `.expo/types` files.
 */
export function href(path: string): Href {
  return path as Href;
}
