import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import Ionicons from '@expo/vector-icons/Ionicons';
import type { CommunityGroup, CommunityPostListResponse } from '@ninibu/types';
import { formatRelativeFa, toPersianDigits } from '@ninibu/datetime';
import { api, apiPaths } from '@/lib/api';
import { Badge, Button, Card, EmptyState, ErrorState, Header, IconButton, Loading, Screen, SectionTitle } from '@/components/ui';
import { colors } from '@/theme';

export default function GroupDetail(){const {groupId}=useLocalSearchParams<{groupId:string}>();const id=Number(groupId);const [group,setGroup]=useState<CommunityGroup>();const [posts,setPosts]=useState<CommunityPostListResponse>();const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
async function load(){if(!id)return;setLoading(true);setError('');try{const g=await api<CommunityGroup>(apiPaths.communityGroup(id));setGroup(g);if(g.visibility==='public'||g.membership_status==='active'){try{setPosts(await api<CommunityPostListResponse>(`${apiPaths.communityGroupPosts(id)}?limit=50`))}catch{setPosts(undefined)}}else setPosts(undefined)}catch(e){setError(e instanceof Error?e.message:'خطا در دریافت گروه')}finally{setLoading(false)}}useEffect(()=>{void load()},[id]);
async function toggle(){if(!group)return;setBusy(true);setError('');try{if(group.membership_status==='active')await api(apiPaths.communityGroupLeave(group.id),{method:'POST'});else await api(apiPaths.communityGroupJoin(group.id),{method:'POST'});await load()}catch(e){setError(e instanceof Error?e.message:'عملیات عضویت انجام نشد')}finally{setBusy(false)}}
return <Screen refreshing={loading} onRefresh={load}><Header title={group?.name||'گروه'} subtitle="جامعه نینیبو" right={<IconButton icon="arrow-forward" onPress={()=>router.back()}/>}/>{error?<ErrorState message={error} onRetry={load}/>:loading?<Loading/>:group?<><Card><View style={s.top}><View style={s.icon}><Ionicons name="people" size={23} color={colors.primary}/></View><View style={{flex:1}}><View style={s.titleRow}><Text style={s.title}>{group.name}</Text>{group.is_official?<Badge tone="pink">رسمی</Badge>:null}</View><Text style={s.meta}>{toPersianDigits(group.member_count)} عضو · {group.category.name}</Text></View></View>{group.description?<Text style={s.desc}>{group.description}</Text>:null}<View style={s.badges}><Badge tone={group.visibility==='private'?'gray':'green'}>{group.visibility==='private'?'خصوصی':'عمومی'}</Badge>{group.membership_status==='pending'?<Badge tone="warning">در انتظار تأیید</Badge>:group.membership_status==='active'?<Badge tone="green">عضو هستید</Badge>:null}</View>{group.membership_policy!=='invitation_only'?<Button title={group.membership_status==='active'?'خروج از گروه':group.membership_status==='pending'?'درخواست ثبت شده':'عضویت در گروه'} variant={group.membership_status==='active'?'ghost':'secondary'} loading={busy} disabled={group.membership_status==='pending'} onPress={toggle}/>:<Text style={s.notice}>عضویت این گروه فقط با دعوت امکان‌پذیر است.</Text>}</Card><SectionTitle kicker="گفت‌وگوها" title="پست‌های گروه"/>{group.visibility==='private'&&group.membership_status!=='active'?<EmptyState icon="lock-closed-outline" title="محتوای این گروه خصوصی است" text="بعد از تأیید عضویت می‌توانید پست‌های گروه را ببینید."/>:posts?.items.length?posts.items.map(p=><Pressable key={p.id} onPress={()=>router.push({pathname:'/(app)/community/posts/[postId]',params:{postId:String(p.id)}})}><Card><Text style={s.postMeta}>{p.author.display_name} · {formatRelativeFa(p.published_at)}</Text>{p.title?<Text style={s.postTitle}>{p.title}</Text>:null}<Text style={s.postBody} numberOfLines={5}>{p.body}</Text><Text style={s.postMeta}>💬 {toPersianDigits(p.comment_count)} دیدگاه</Text></Card></Pressable>):<EmptyState title="هنوز پستی در این گروه نیست"/>}</>:<EmptyState title="گروه پیدا نشد"/>}</Screen>}
const s=StyleSheet.create({top:{flexDirection:'row-reverse',gap:12,alignItems:'center'},icon:{width:48,height:48,borderRadius:17,backgroundColor:colors.primarySoft,alignItems:'center',justifyContent:'center'},titleRow:{flexDirection:'row-reverse',gap:8,alignItems:'center'},title:{fontSize:18,fontWeight:'900',textAlign:'right',writingDirection:'rtl'},meta:{fontSize:10.5,color:colors.muted,textAlign:'right',writingDirection:'rtl',marginTop:4},desc:{fontSize:12.5,color:colors.foreground,textAlign:'right',writingDirection:'rtl',lineHeight:22,marginTop:14},badges:{flexDirection:'row-reverse',gap:7,marginVertical:12},notice:{fontSize:11,color:colors.muted,textAlign:'right',writingDirection:'rtl'},postMeta:{fontSize:10.5,color:colors.muted,textAlign:'right',writingDirection:'rtl'},postTitle:{fontSize:15,fontWeight:'900',textAlign:'right',writingDirection:'rtl',marginTop:8},postBody:{fontSize:12.5,lineHeight:22,textAlign:'right',writingDirection:'rtl',marginTop:6}})
