export const apiPaths = {
  requestOtp: "/api/v1/auth/request-otp",
  verifyOtp: "/api/v1/auth/verify-otp",
  refresh: "/api/v1/auth/refresh",
  me: "/api/v1/auth/me",
  logout: "/api/v1/auth/logout",
  profile: "/api/v1/profile",
  onboardingComplete: "/api/v1/profile/onboarding/complete",
  countries: "/api/v1/geo/countries",
  provinces: "/api/v1/geo/provinces",
  cities: "/api/v1/geo/cities",
  children: "/api/v1/children",
  recommendations: "/api/v1/recommendations",
  notificationUnreadCount: "/api/v1/notifications/unread-count",
  childGrowthMeasurements: (childId: number | string) => `/api/v1/children/${childId}/growth-measurements`,
  childGrowthChart: (childId: number | string) => `/api/v1/children/${childId}/growth-chart`,
  childVaccinations: (childId: number | string) => `/api/v1/children/${childId}/vaccinations`,
  childAllergies: (childId: number | string) => `/api/v1/children/${childId}/allergies`,
  childMedicalVisits: (childId: number | string) => `/api/v1/children/${childId}/medical-visits`,
  childMedications: (childId: number | string) => `/api/v1/children/${childId}/medications`,
  childHealthTimeline: (childId: number | string) => `/api/v1/children/${childId}/health-timeline`,
  communityCategories: "/api/v1/community/categories",
  communityProfile: "/api/v1/community/profile",
  communityGroups: "/api/v1/community/groups",
  communityGroup: (groupId: number | string) => `/api/v1/community/groups/${groupId}`,
  communityGroupJoin: (groupId: number | string) => `/api/v1/community/groups/${groupId}/join`,
  communityGroupLeave: (groupId: number | string) => `/api/v1/community/groups/${groupId}/leave`,
  communityGroupPosts: (groupId: number | string) => `/api/v1/community/groups/${groupId}/posts`,
  communityFeed: "/api/v1/community/feed",
  communityPost: (postId: number | string) => `/api/v1/community/posts/${postId}`,
  communityPostComments: (postId: number | string) => `/api/v1/community/posts/${postId}/comments`,
  communityPostReactions: (postId: number | string) => `/api/v1/community/posts/${postId}/reactions`,
  communityPostReaction: (postId: number | string, reactionType: string) => `/api/v1/community/posts/${postId}/reactions/${reactionType}`,
  communityComment: (commentId: number | string) => `/api/v1/community/comments/${commentId}`,
  communityCommentReactions: (commentId: number | string) => `/api/v1/community/comments/${commentId}/reactions`,
  communityCommentReaction: (commentId: number | string, reactionType: string) => `/api/v1/community/comments/${commentId}/reactions/${reactionType}`,
  communityReports: "/api/v1/community/reports",
  consultationCategories: "/api/v1/consultations/categories",
  consultationPublicQuestions: "/api/v1/consultations/public/questions",
  consultationQuestions: "/api/v1/consultations/questions",
  consultationQuestion: (questionId: number | string) => `/api/v1/consultations/questions/${questionId}`,
  consultationQuestionAnswers: (questionId: number | string) => `/api/v1/consultations/questions/${questionId}/answers`,
  consultationAnswerAccept: (questionId: number | string, answerId: number | string) => `/api/v1/consultations/questions/${questionId}/answers/${answerId}/accept`,
  consultationQuestionClose: (questionId: number | string) => `/api/v1/consultations/questions/${questionId}/close`,
  consultationQuestionReopen: (questionId: number | string) => `/api/v1/consultations/questions/${questionId}/reopen`,
  consultationQuestionSuggestions: (questionId: number | string) => `/api/v1/consultations/questions/${questionId}/suggestions`,
  commerceCategories: "/api/v1/commerce/categories",
  commerceServices: "/api/v1/commerce/services",
  commerceService: (serviceId: number | string) => `/api/v1/commerce/services/${serviceId}`,
  serviceAvailability: (serviceId: number | string) => `/api/v1/commerce/services/${serviceId}/available-slots`,
  bookings: "/api/v1/bookings",
  booking: (bookingId: number | string) => `/api/v1/bookings/${bookingId}`,
  bookingCancel: (bookingId: number | string) => `/api/v1/bookings/${bookingId}/cancel`,
  bookingReschedule: (bookingId: number | string) => `/api/v1/bookings/${bookingId}/reschedule`,
  orderPayments: (orderId: number | string) => `/api/v1/commerce/orders/${orderId}/payments`,
  payment: (paymentId: number | string) => `/api/v1/payments/${paymentId}`,
  sandboxPaymentSucceed: (paymentId: number | string) => `/api/v1/payments/sandbox/${paymentId}/succeed`,
  sandboxPaymentFail: (paymentId: number | string) => `/api/v1/payments/sandbox/${paymentId}/fail`
} as const;
