export const apiPaths = {
  login: "/api/v1/auth/login",
  adminLogin: "/api/v1/auth/admin/login",
  signupRequestOtp: "/api/v1/auth/signup/request-otp",
  signup: "/api/v1/auth/signup",
  passwordForgotRequestOtp: "/api/v1/auth/password/forgot/request-otp",
  passwordReset: "/api/v1/auth/password/reset",
  requestOtp: "/api/v1/auth/request-otp",
  verifyOtp: "/api/v1/auth/verify-otp",
  refresh: "/api/v1/auth/refresh",
  me: "/api/v1/auth/me",
  logout: "/api/v1/auth/logout",
  profile: "/api/v1/profile",
  onboardingComplete: "/api/v1/profile/onboarding/complete",
  countries: "/api/v1/geo/countries",
  provinces: "/api/v1/geo/provinces",
  cities: "/api/v1/geo/cities",
  children: "/api/v1/children",
  recommendations: "/api/v1/recommendations",
  notificationUnreadCount: "/api/v1/notifications/unread-count",
  childGrowthMeasurements: (childId: number | string) => `/api/v1/children/${childId}/growth-measurements`,
  childGrowthChart: (childId: number | string) => `/api/v1/children/${childId}/growth-chart`,
  childDocumentGrowthImport: (childId: number | string) => `/api/v1/children/${childId}/document-imports/growth-chart`,
  childDocumentImport: (childId: number | string, importId: number | string) => `/api/v1/children/${childId}/document-imports/${importId}`,
  childDocumentImportConfirm: (childId: number | string, importId: number | string) => `/api/v1/children/${childId}/document-imports/${importId}/confirm`,
  childVaccinations: (childId: number | string) => `/api/v1/children/${childId}/vaccinations`,
  childAllergies: (childId: number | string) => `/api/v1/children/${childId}/allergies`,
  childMedicalVisits: (childId: number | string) => `/api/v1/children/${childId}/medical-visits`,
  childMedications: (childId: number | string) => `/api/v1/children/${childId}/medications`,
  childHealthTimeline: (childId: number | string) => `/api/v1/children/${childId}/health-timeline`,
  communityCategories: "/api/v1/community/categories",
  communityProfile: "/api/v1/community/profile",
  communityGroups: "/api/v1/community/groups",
  communityGroup: (groupId: number | string) => `/api/v1/community/groups/${groupId}`,
  communityGroupJoin: (groupId: number | string) => `/api/v1/community/groups/${groupId}/join`,
  communityGroupLeave: (groupId: number | string) => `/api/v1/community/groups/${groupId}/leave`,
  communityGroupPosts: (groupId: number | string) => `/api/v1/community/groups/${groupId}/posts`,
  communityFeed: "/api/v1/community/feed",
  communityPost: (postId: number | string) => `/api/v1/community/posts/${postId}`,
  communityPostComments: (postId: number | string) => `/api/v1/community/posts/${postId}/comments`,
  communityPostReactions: (postId: number | string) => `/api/v1/community/posts/${postId}/reactions`,
  communityPostReaction: (postId: number | string, reactionType: string) => `/api/v1/community/posts/${postId}/reactions/${reactionType}`,
  communityComment: (commentId: number | string) => `/api/v1/community/comments/${commentId}`,
  communityCommentReactions: (commentId: number | string) => `/api/v1/community/comments/${commentId}/reactions`,
  communityCommentReaction: (commentId: number | string, reactionType: string) => `/api/v1/community/comments/${commentId}/reactions/${reactionType}`,
  communityReports: "/api/v1/community/reports",
  consultationCategories: "/api/v1/consultations/categories",
  consultationPublicQuestions: "/api/v1/consultations/public/questions",
  consultationQuestions: "/api/v1/consultations/questions",
  consultationQuestion: (questionId: number | string) => `/api/v1/consultations/questions/${questionId}`,
  consultationQuestionAnswers: (questionId: number | string) => `/api/v1/consultations/questions/${questionId}/answers`,
  consultationAnswerAccept: (questionId: number | string, answerId: number | string) => `/api/v1/consultations/questions/${questionId}/answers/${answerId}/accept`,
  consultationQuestionClose: (questionId: number | string) => `/api/v1/consultations/questions/${questionId}/close`,
  consultationQuestionReopen: (questionId: number | string) => `/api/v1/consultations/questions/${questionId}/reopen`,
  consultationQuestionSuggestions: (questionId: number | string) => `/api/v1/consultations/questions/${questionId}/suggestions`,
  commerceCategories: "/api/v1/commerce/categories",
  commerceProducts: "/api/v1/commerce/products",
  commerceProduct: (productId: number | string) => `/api/v1/commerce/products/${productId}`,
  commerceCart: "/api/v1/commerce/cart",
  commerceCartItems: "/api/v1/commerce/cart/items",
  commerceCartItem: (itemId: number | string) => `/api/v1/commerce/cart/items/${itemId}`,
  commerceCheckoutPreview: "/api/v1/commerce/checkout/preview",
  commerceOrders: "/api/v1/commerce/orders",
  commerceOrder: (orderId: number | string) => `/api/v1/commerce/orders/${orderId}`,
  commerceOrderCancel: (orderId: number | string) => `/api/v1/commerce/orders/${orderId}/cancel`,
  commerceServices: "/api/v1/commerce/services",
  commerceService: (serviceId: number | string) => `/api/v1/commerce/services/${serviceId}`,
  serviceAvailability: (serviceId: number | string) => `/api/v1/commerce/services/${serviceId}/available-slots`,
  bookings: "/api/v1/bookings",
  booking: (bookingId: number | string) => `/api/v1/bookings/${bookingId}`,
  bookingCancel: (bookingId: number | string) => `/api/v1/bookings/${bookingId}/cancel`,
  bookingReschedule: (bookingId: number | string) => `/api/v1/bookings/${bookingId}/reschedule`,
  orderPayments: (orderId: number | string) => `/api/v1/commerce/orders/${orderId}/payments`,
  payment: (paymentId: number | string) => `/api/v1/payments/${paymentId}`,
  sandboxPaymentSucceed: (paymentId: number | string) => `/api/v1/payments/sandbox/${paymentId}/succeed`,
  sandboxPaymentFail: (paymentId: number | string) => `/api/v1/payments/sandbox/${paymentId}/fail`,
  content: "/api/v1/content",
  contentCategories: "/api/v1/content/categories",
  contentTags: "/api/v1/content/tags",
  contentDetail: (slug: string) => `/api/v1/content/${encodeURIComponent(slug)}`,
  contentRelated: (contentId: number | string) => `/api/v1/content/${contentId}/related`,
  contentBookmarks: "/api/v1/content/bookmarks",
  contentBookmark: (contentId: number | string) => `/api/v1/content/${contentId}/bookmark`,
  contentInteractions: (contentId: number | string) => `/api/v1/content/${contentId}/interactions`,
  search: "/api/v1/search",
  searchSuggestions: "/api/v1/search/suggestions",
  searchTrending: "/api/v1/search/trending",
  searchHistory: "/api/v1/search/history",
  searchHistoryItem: (historyId: number | string) => `/api/v1/search/history/${historyId}`,
  searchEvents: "/api/v1/search/events",
  careLocationDiscover: "/api/v1/care-locations/discover",
  personalizationFeed: "/api/v1/recommendations/feed",
  personalizationFeedback: (recommendationId: number | string) => `/api/v1/recommendations/${recommendationId}/feedback`,
  personalizationSignal: "/api/v1/personalization/signals",
  advertisingPlacementItems: (placementCode: string) => `/api/v1/advertising/placements/${encodeURIComponent(placementCode)}/items`,
  advertisingEvents: "/api/v1/advertising/events",
  advertisingPreferences: "/api/v1/advertising/preferences",
  maternalHealthProfile: "/api/v1/maternal-health/profile",
  maternalHealthGuidance: "/api/v1/maternal-health/guidance",
  maternalHealthCycles: "/api/v1/maternal-health/cycles",
  maternalHealthBreastfeeding: "/api/v1/maternal-health/breastfeeding",
  maternalHealthCheckIns: "/api/v1/maternal-health/check-ins",
  childNutritionRecommendations: (childId: number | string) => `/api/v1/children/${childId}/nutrition-recommendations`,
  adminDashboard: "/api/v1/admin/backoffice/dashboard",
  adminUsers: "/api/v1/admin/backoffice/users",
  adminUserStatus: (userId: number | string) => `/api/v1/admin/backoffice/users/${userId}/status`,
  adminUserRole: (userId: number | string) => `/api/v1/admin/backoffice/users/${userId}/role`,
  adminProviders: "/api/v1/admin/backoffice/providers",
  adminFinance: "/api/v1/admin/backoffice/finance",
  adminFeatureFlags: "/api/v1/admin/backoffice/feature-flags",
  adminFeatureFlag: (code: string) => `/api/v1/admin/backoffice/feature-flags/${encodeURIComponent(code)}`,
  adminSettings: "/api/v1/admin/backoffice/settings",
  adminSetting: (key: string) => `/api/v1/admin/backoffice/settings/${encodeURIComponent(key)}`,
  adminAuditEvents: "/api/v1/admin/backoffice/audit-events",
  adminContent: "/api/v1/admin/content",
  adminContentItem: (contentId: number | string) => `/api/v1/admin/content/${contentId}`,
  adminContentSubmitReview: (contentId: number | string) => `/api/v1/admin/content/${contentId}/submit-review`,
  adminContentPublish: (contentId: number | string) => `/api/v1/admin/content/${contentId}/publish`,
  adminContentArchive: (contentId: number | string) => `/api/v1/admin/content/${contentId}/archive`,
  adminAdvertisers: "/api/v1/admin/advertising/advertisers",
  adminAdvertiser: (advertiserId: number | string) => `/api/v1/admin/advertising/advertisers/${advertiserId}`,
  adminAdCampaigns: "/api/v1/admin/advertising/campaigns",
  adminAdCampaignApprove: (campaignId: number | string) => `/api/v1/admin/advertising/campaigns/${campaignId}/approve`,
  adminAdCampaignReject: (campaignId: number | string) => `/api/v1/admin/advertising/campaigns/${campaignId}/reject`,
  adminAdCampaignPause: (campaignId: number | string) => `/api/v1/admin/advertising/campaigns/${campaignId}/pause`,
  adminAdReports: "/api/v1/admin/advertising/reports",
  adminCommunityGroups: "/api/v1/admin/community/groups",
  adminCommunityReports: "/api/v1/admin/community/reports",
  adminCommunityReportReview: (reportId: number | string) => `/api/v1/admin/community/reports/${reportId}/review`,
  adminSellers: "/api/v1/admin/commerce/sellers",
  adminSellerVerify: (sellerId: number | string) => `/api/v1/admin/commerce/sellers/${sellerId}/verify`,
  adminSellerReject: (sellerId: number | string) => `/api/v1/admin/commerce/sellers/${sellerId}/reject`,
  adminSellerSuspend: (sellerId: number | string) => `/api/v1/admin/commerce/sellers/${sellerId}/suspend`,
  adminClinicianVerification: (profileId: number | string) => `/api/v1/admin/clinicians/${profileId}/verification`,
  adminReviews: "/api/v1/admin/reviews",
  adminReviewReports: "/api/v1/admin/reviews/reports",
  adminRefunds: "/api/v1/admin/refunds"
} as const;

export const notificationApiPaths = {
  notifications: "/api/v1/notifications",
  notificationRead: (notificationId: string | number) => `/api/v1/notifications/${notificationId}/read`,
  notificationsReadAll: "/api/v1/notifications/read-all",
  notificationPreferences: "/api/v1/notification-preferences"
} as const;
