// Auto-generated by scripts/mobile-font-prepare.mjs
// Medium is optional: when it is not present, typography.medium uses the Regular FaNum family.
export const HAS_YEKANBAKH_FANUM = true as const;
export const HAS_YEKANBAKH_FANUM_MEDIUM = false as const;
export const NINIBU_FONT_ASSETS = {
  YekanBakhFaNum: require('../../assets/fonts/YekanBakhFaNum-Regular.ttf'),
  YekanBakhFaNumBold: require('../../assets/fonts/YekanBakhFaNum-Bold.ttf'),
} as const;
export const NINIBU_FONT_FAMILY = { regular: 'YekanBakhFaNum', medium: 'YekanBakhFaNum', bold: 'YekanBakhFaNumBold' } as const;
