import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Switch, Text, View } from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';
import type { NotificationItem, NotificationListResponse, NotificationPreference, UpdateNotificationPreferencesRequest } from '@ninibu/types';
import { formatJalaliDateTime } from '@ninibu/datetime';
import { api, notificationApiPaths } from '@/lib/api';
import { Badge, Button, Card, EmptyState, ErrorState, Header, Loading, Screen, SectionTitle } from '@/components/ui';
import { colors } from '@/theme';

type Mode='all'|'unread'|'settings';
const categoryLabel:Record<string,string>={health:'سلامت',growth:'رشد',vaccination:'واکسن',consultation:'مشاوره',booking:'رزرو',commerce:'خرید',advertising:'پیشنهاد تجاری',system:'سیستم'};
export default function Notifications(){
 const [mode,setMode]=useState<Mode>('all');const [items,setItems]=useState<NotificationItem[]>([]);const [prefs,setPrefs]=useState<NotificationPreference[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');
 async function load(){setLoading(true);setError('');try{if(mode==='settings')setPrefs(await api<NotificationPreference[]>(notificationApiPaths.notificationPreferences));else{const r=await api<NotificationListResponse>(`${notificationApiPaths.notifications}?page=1&limit=50&unread_only=${mode==='unread'?'true':'false'}`);setItems(r.items)}}catch(e){setError(e instanceof Error?e.message:'خطا در دریافت اعلان‌ها')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[mode]);
 async function markRead(item:NotificationItem){if(item.status==='read')return;try{const next=await api<NotificationItem>(notificationApiPaths.notificationRead(item.id),{method:'POST'});setItems(x=>x.map(v=>v.id===item.id?next:v))}catch(e){setError(e instanceof Error?e.message:'ثبت وضعیت اعلان ناموفق بود')}}
 async function markAll(){setSaving(true);setError('');try{await api(notificationApiPaths.notificationsReadAll,{method:'POST'});await load()}catch(e){setError(e instanceof Error?e.message:'ثبت اعلان‌ها ناموفق بود')}finally{setSaving(false)}}
 async function savePrefs(){setSaving(true);setError('');try{const body:UpdateNotificationPreferencesRequest={items:prefs.map(x=>({category:x.category,in_app_enabled:x.in_app_enabled,quiet_hours_start:x.quiet_hours_start,quiet_hours_end:x.quiet_hours_end,timezone:x.timezone||'Asia/Tehran'}))};setPrefs(await api<NotificationPreference[]>(notificationApiPaths.notificationPreferences,{method:'PATCH',body:JSON.stringify(body)}))}catch(e){setError(e instanceof Error?e.message:'ذخیره تنظیمات ناموفق بود')}finally{setSaving(false)}}
 return <Screen refreshing={loading} onRefresh={load}><Header title="اعلان‌ها" subtitle="یادآوری‌ها و رویدادهای مهم نینیبو"/><View style={s.tabs}><Tab active={mode==='all'} label="همه" onPress={()=>setMode('all')}/><Tab active={mode==='unread'} label="خوانده‌نشده" onPress={()=>setMode('unread')}/><Tab active={mode==='settings'} label="تنظیمات" onPress={()=>setMode('settings')}/></View>{error?<ErrorState message={error} onRetry={load}/>:null}{loading?<Loading/>:mode==='settings'?<><SectionTitle kicker="کنترل شما" title="تنظیم اعلان‌های داخل برنامه"/><Card><Text style={s.notice}>کانال‌های Push، پیامک و ایمیل در این نسخه نمایش داده می‌شوند اما فقط تنظیم اعلان داخل برنامه از اپ قابل تغییر است.</Text>{prefs.map((p,i)=><View key={p.category} style={s.pref}><View style={{flex:1}}><Text style={s.prefTitle}>{categoryLabel[p.category]||p.category}</Text><Text style={s.prefSub}>{p.in_app_enabled?'اعلان داخل برنامه روشن است':'اعلان داخل برنامه خاموش است'}</Text></View><Switch value={p.in_app_enabled} onValueChange={v=>setPrefs(cur=>cur.map((x,j)=>j===i?{...x,in_app_enabled:v}:x))} trackColor={{false:'#D8D3DE',true:colors.primarySoft}} thumbColor={p.in_app_enabled?colors.primary:'#8B8492'}/></View>)}<Button title="ذخیره تنظیمات" onPress={savePrefs} loading={saving}/></Card></>:<><View style={s.toolbar}><Text style={s.count}>{new Intl.NumberFormat('fa-IR').format(items.filter(x=>x.status!=='read').length)} خوانده‌نشده</Text><Button title="خواندن همه" variant="secondary" onPress={markAll} loading={saving} disabled={!items.some(x=>x.status!=='read')}/></View>{items.length?items.map(item=><Pressable key={item.id} onPress={()=>void markRead(item)}><Card style={[s.notification,item.status!=='read'&&s.unread]}><View style={s.top}><Badge tone={item.priority==='high'?'warning':'purple'}>{categoryLabel[item.category]||item.category}</Badge>{item.status!=='read'?<View style={s.unreadDot}/>:null}</View><Text style={s.title}>{item.title}</Text><Text style={s.body}>{item.body}</Text><Text style={s.time}>{formatJalaliDateTime(item.sent_at||item.created_at)}</Text></Card></Pressable>):<EmptyState icon="notifications-off-outline" title={mode==='unread'?'اعلان خوانده‌نشده‌ای ندارید':'هنوز اعلانی ندارید'} text="یادآوری‌ها و رویدادهای مهم اینجا دیده می‌شوند."/>}</>}</Screen>
}
function Tab({active,label,onPress}:{active:boolean;label:string;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.tab,active&&s.activeTab]}><Text style={[s.tabText,active&&s.activeTabText]}>{label}</Text></Pressable>}
const s=StyleSheet.create({tabs:{flexDirection:'row-reverse',gap:7,backgroundColor:'#E9E6EE',padding:4,borderRadius:15},tab:{flex:1,minHeight:39,alignItems:'center',justifyContent:'center',borderRadius:12},activeTab:{backgroundColor:'#fff'},tabText:{fontSize:11.5,fontWeight:'800',color:colors.muted,writingDirection:'rtl'},activeTabText:{color:colors.primaryStrong},toolbar:{flexDirection:'row-reverse',alignItems:'center',justifyContent:'space-between',gap:12},count:{fontSize:11,color:colors.muted,writingDirection:'rtl'},notification:{gap:7},unread:{borderColor:'#CFC5F3',backgroundColor:'#FCFBFF'},top:{flexDirection:'row-reverse',justifyContent:'space-between',alignItems:'center'},unreadDot:{width:8,height:8,borderRadius:4,backgroundColor:colors.accent},title:{fontSize:14,fontWeight:'900',textAlign:'right',writingDirection:'rtl',color:colors.foreground},body:{fontSize:11.5,lineHeight:19,textAlign:'right',writingDirection:'rtl',color:colors.muted},time:{fontSize:9.5,textAlign:'right',color:colors.muted},notice:{fontSize:11.5,lineHeight:20,textAlign:'right',writingDirection:'rtl',color:colors.muted,backgroundColor:colors.primarySoft,borderRadius:14,padding:12,marginBottom:4},pref:{flexDirection:'row-reverse',alignItems:'center',gap:10,paddingVertical:13,borderBottomWidth:1,borderBottomColor:colors.border},prefTitle:{fontSize:13,fontWeight:'900',textAlign:'right',writingDirection:'rtl'},prefSub:{fontSize:10.5,color:colors.muted,textAlign:'right',writingDirection:'rtl',marginTop:3}})
